# stages
stages:
  # commit messages
  - commit-check
  # code check
  - code-check
  # docs check
  - docs-check
  # functional tests
  - functional-tests
  # system tests
  - system-tests

# commit messages
commit-messages:
  stage: commit-check
  tags:
    - sonic-runner
  script:
    - python3 ./cicd/check-commit-message.py

# files check
check-files:
  stage: commit-check
  tags:
    - sonic-runner
  script:
    - ./cicd/check-files.sh

# code-linter
code-linter:
  stage: code-check
  tags:
    - sonic-runner
  script:
    - ./cicd/code-linter.sh

# code-style
code-style:
  stage: code-check
  tags:
    - sonic-runner
  script:
    - ./cicd/code-formatter.sh

# docstring-check
docstring-check:
  stage: code-check
  tags:
    - sonic-runner
  script:
    - ./cicd/docstring-check.sh

# docs-linter
docs-linter:
  stage: docs-check
  tags:
    - sonic-runner
  script:
    - ./cicd/docs-linter.sh

# ut (qcos)
ut-qcos:
  stage: functional-tests
  tags:
    - sonic-runner
  script:
    - ./cicd/run-tests.sh -u default
  artifacts:
    when: always
    reports:
      junit: cicd/reports/wy_qcos/report.xml

# code-coverage (qcos)
code-coverage-qcos:
  stage: functional-tests
  tags:
    - sonic-runner
  script:
    - ./cicd/run-tests.sh -c default
  coverage: '/(?i)total.*? (100(?:\.0+)?\%|[1-9]?\d(?:\.\d+)?\%)/'

# ut (qcos_client)
ut-qcos-client:
  stage: functional-tests
  tags:
    - sonic-runner
  script:
    - ./cicd/run-tests.sh -j all

# code-coverage (qcos_client)
code-coverage-qcos-client:
  stage: functional-tests
  tags:
    - sonic-runner
  script:
    - ./cicd/run-tests.sh -e all

# system tests
#st:
#  stage: system-tests
#  tags:
#    - sonic-runner
#  script:
#    - ./cicd/run-tests.sh -s all

# stress tests
#stress:
#  stage: system-tests
#  tags:
#    - sonic-runner
#  script:
#    - ./cicd/run-tests.sh -s all
