# stages
stages:
  - commit
  # Test
  - test

# commit messages
commit-messages:
  stage: commit
  tags:
    - sonic-runner
  script:
    - python3 ./cicd/check-commit-message.py


# code-linter
code-linter:
  stage: test
  tags:
    - sonic-runner
  script:
    - ./cicd/code-linter.sh

# code-style
code-style:
  stage: test
  tags:
    - sonic-runner
  script:
    - ./cicd/code-formatter.sh

# ut
ut:
  stage: test
  tags:
    - sonic-runner
  script:
    - ./cicd/run-tests.sh -u
  artifacts:
    when: always
    reports:
      junit: cicd/report.xml

# code-coverage
code-coverage:
  stage: test
  tags:
    - sonic-runner
  script:
    - ./cicd/run-tests.sh -c
  coverage: '/^TOTAL\s+\S+\s+\S+\s+(\d+)%$/'

# st
#st:
#  stage: test
#  tags:
#    - sonic-runner
#  script:
#    - ./cicd/run-tests.sh -s
