# Read the Docs configs

version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.11"
    nodejs: "20"
  apt_packages:
    - default-jre
    - graphviz
    - plantuml
    - imagemagick
    - librsvg2-bin
    - fonts-noto-cjk
    - cmake
    - build-essential
  jobs:
    post_install:
      - npm install -g @mermaid-js/mermaid-cli plantuml

sphinx:
  configuration: docs/sphinx/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

formats:
  - pdf
  - htmlzip
#   - epub
