[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools>=61.0", "wheel>=0.37.1"]

[project]
name = "wy-qcos"
version = "1.1.0"
description = """WuYue QCOS (Quantum Computing Operating System), \
is an open-source, general-purpose Quantum Computing Operating System \
designed to provide unified software support for quantum computers of \
diverse architectures \
(e.g., SuperConducting, Neutral Atom, Ion Trap, Coherent Ising Machine, \
NMR, etc.) and drive the ecological development of quantum computing. \
"""
readme = "README.md"
requires-python = ">=3.11,<3.13"
license = { file = "LICENSE" }
authors = [
    {name = "Zhao Yi", email = "zhaoyi_yewu@cmss.chinamobile.com"},
    {name = "Ji Dalong", email = "jidalong_yewu@cmss.chinamobile.com"},
    {name = "Xu Dong", email = "xudong_yewu@cmss.chinamobile.com"},
    {name = "Wu Fangwei", email = "wufangwei_yewu@cmss.chinamobile.com"},
    {name = "Guo Zhufeng", email = "guozhufeng_yewu@cmss.chinamobile.com"},
    {name = "Liu Zhifeng", email = "liuzhifeng_yewu@cmss.chinamobile.com"},
    {name = "Zhou Yunxiao", email = "zhouyunxiao_yewu@cmss.chinamobile.com"},
    {name = "Ye Zhiwei", email = "yezhiwei_yewu@cmss.chinamobile.com"},
    {name = "Huang Yachao", email = "huangyachao_yewu@cmss.chinamobile.com"},
    {name = "Wang Jujun", email = "wangjujun_yewu@cmss.chinamobile.com"},
    {name = "Lian Wencong", email = "lianwencong_yewu@cmss.chinamobile.com"},
    {name = "Xu Yu", email = "xuyu2_yewu@cmss.chinamobile.com"}
]
keywords = ["qcos", "quantum", "operating", "system"]

# Add PyPI classifiers here
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Natural Language :: English",
    "Operating System :: POSIX",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: Implementation :: CPython",
]

# Required dependencies for install/usage of your package or application
# If you don't have any dependencies, leave this section empty
# Format for dependency strings: https://peps.python.org/pep-0508/
dependencies = [
    # requirements
    "aiohttp==3.12.13",
    "alembic==1.16.3",
    "annotated-types==0.7.0",
    "anyio==4.9.0",
    "argcomplete==3.6.2",
    "bcrypt==5.0.0",
    "click==8.1.8",
    "cliff==4.10.0",
    "cryptography==45.0.7",
    "fastapi==0.122.1",
    "fastapi-jsonrpc==3.4.2",
    "h11==0.16.0",
    "httpcore==1.0.9",
    "httpx==0.28.1",
    "idna==3.10",
    "jsonrpcclient==4.0.3",
    "loguru==0.7.3",
    "matplotlib==3.10.8",
    "mqt.qcec==3.3.0",
    "networkx==3.3",
    "numexpr==2.14.1",
    "numpy==1.26.4",
    "openpulse==1.0.1",
    "openqasm3==1.0.1",
    "opentelemetry-api==1.39.1",
    "oqpy==0.3.10",
    "pallets-sphinx-themes==2.3.0",
    "pg8000==1.31.5",
    "ply==3.11",
    "poetry==2.1.3",
    "prefect==3.6.9; sys_platform == 'linux'",
    "prometheus-client==0.21.1",
    "psutil==7.1.3",
    "pulp==3.2.2",
    "pwdlib==0.3.0",
    "pycasbin==2.8.0",
    "pydantic==2.11.5",
    "pydantic_core==2.33.2",
    "pydocket==0.16.3",
    "PyJWT==2.12.1",
    "pytest==8.4.1",
    "pytest-cov==6.2.1",
    "python-jose==3.5.0",
    "python-socketio==5.12.1",
    "redis==7.1.0",
    "requests==2.32.5",
    "rustworkx==0.17.1",
    "schema==0.7.7",
    "scipy==1.17.0",
    "setproctitle==1.3.7",
    "sniffio==1.3.1",
    "sqlalchemy==2.0.48",
    "sqlalchemy-adapter==1.9.0",
    "sqlalchemy-utils==0.42.1",
    "starlette==0.50.0",
    "tomlkit==0.13.3",
    "typing-inspection==0.4.1",
    "typing_extensions==4.15.0",
    "uvicorn==0.34.2",
    "wheel==0.45.1",
    "zerorpc==0.6.3",  # driver: hanyuan1 only

    # requirements-test
    "bandit>=1.8.6",
    "flake8>=7.3.0",
    "mypy==1.8.0",
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
    "ruff==0.12.3",
    "sphinx==8.1.3",
    "sphinx-rtd-theme==3.0.2",
    "sphinxcontrib-napoleon==0.7",
    "tabulate==0.9.0",
    "tomli==2.2.1",
    "tox==4.8.0",
]

[project.scripts]
# Command line interface entrypoint scripts
qcos-api = "wy_qcos.api_server:main"
qcos-transpiler = "wy_qcos.transpiler.cmss.transpiler_cmd_line:main"
qiskit-transpiler = "wy_qcos.transpiler.qiskit.transpiler_qiskit_cmd:main"

[project.urls]
"Homepage" = "https://gitee.com/OpenWuYue/qcos"
"Documentation" = "https://qcos.readthedocs.io"
"Changelog" = "https://gitee.com/OpenWuYue/qcos/blob/develop/CHANGELOG.md"
"Issue Tracker" = "https://gitee.com/OpenWuYue/qcos/issues"
"Source" = "https://gitee.com/OpenWuYue/qcos"

[tool.poetry.dependencies]

[tool.setuptools]
include-package-data = true

[tool.setuptools.packages.find]
where = ["src"]
include = ["wy_qcos*"]
exclude = ["wy_qcos_client*"]

[tool.isort]
profile = "black"
force_grid_wrap = "2"
known_first_party = "wy_qcos"

[tool.mypy]
incremental = false
cache_dir = "/dev/null"
pretty = true
show_error_context = true
show_column_numbers = true
warn_unused_ignores = true
check_untyped_defs = false
strict = false
# remove gradually as progress is made
disable_error_code = "import-untyped,var-annotated,import-not-found,union-attr,index"
# honor excludes by not following there through imports
follow_imports = "skip"
files = "src"
exclude = [
    "^venv/",
    ".+/venv/",
    "^\\.venv/",
    ".+/\\.venv/",
    "^.*\\.egg-info/",
    ".+/\\.egg-info/"
]

[tool.ruff]
line-length = 79
target-version = "py310"
# cache-dir = "/tmp/.ruff_cache"
exclude = [
    ".venv/",
    ".git/",
    "__pycache__/",
]

[tool.ruff.lint]
select = ["E", "F", "S", "U", "D", "CPY001"]
ignore = [
    "D100",  # Missing docstring in public module
    "D101",  # Missing docstring in public class
    "D102",  # Missing docstring in public method
    "D103",  # Missing docstring in public function
    "D104",  # Missing docstring in public package
    "D105",  # Missing docstring in magic method
    # "D414",  # Section has no content ("Returns")
    # "D415",  # First line should end with a period, question mark, or exclamation point
    "D107",  # Missing docstring in public package
    # "D205",  # 1 blank line required between summary line and description

    "E731",  # Do not assign a `lambda` expression, use a `def`
    "E741",  # Ambiguous variable name: `l`

    "S104",  # Possible binding to all interfaces
    "S311",  # Standard pseudo-random generators are not suitable for
             # cryptographic purposes
    "S324",  # Probable use of insecure hash functions in `hashlib`: `md5`

    "UP009", # UTF-8 encoding declaration is unnecessary
    "UP031", # Use format specifiers instead of percent format
    "UP032", # Use f-string instead of `format` call
    "UP018", # Unnecessary `int` call (rewrite as a literal)
    "UP024", # Replace aliased errors with `OSError`
    "UP030", # Use implicit references for positional format fields
    "UP038", # Use `X | Y` in `isinstance` call instead of `(X, Y)`
    "UP039", # Unnecessary parentheses after class definition
]

[tool.ruff.lint.per-file-ignores]
"src/wy_qcos/tests/**/*.py" = ["S101"]
"src/wy_qcos_client/tests/**/*.py" = ["S101"]
"src/**/__init__.py" = ["F401"]
"src/wy_qcos/transpiler/cmss/compiler/parser.py" = ["ALL"]
"src/wy_qcos/transpiler/cmss/compiler/tokrules.py" = ["ALL"]
"src/wy_qcos/transpiler/cmss/compiler/visitor.py" = ["ALL"]

[tool.ruff.lint.isort]
known-first-party = ["wy_qcos"]
known-third-party = ["requests", "pandas", "numpy"]
lines-after-imports = 2

[tool.ruff.lint.flake8-copyright]
notice-rgx = "(?s)^#!/usr/bin/env python3.*?(coding: utf-8).*?(Copyright© 2024-20\\d{2} China Mobile \\(SuZhou\\)).*?(qcos is licensed under Mulan PSL v2).*"

[tool.ruff.lint.pydocstyle]
convention = "google"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
docstring-code-format = true
skip-magic-trailing-comma = false
line-ending = "lf"
exclude = [
    "src/wy_qcos/transpiler/cmss/compiler/parser.py",
    "src/wy_qcos/transpiler/cmss/compiler/tokrules.py",
    "src/wy_qcos/transpiler/cmss/compiler/visitor.py",
]

[tool.doc8]
# ignore = ["D001"]
paths = ["docs/sphinx/source/"]
extension = [".rst"]
max-line-length = 120
ignore-path = [
    "docs/sphinx/source/user-guide/compatibility.rst",
    "docs/sphinx/source/other-docs/code-of-conduct.rst",
    "docs/sphinx/source/other-docs/changelog.rst",
]

[tool.poetry.extras]
docs = ["Sphinx", "sphinx-rtd-theme", "sphinxcontrib-napoleon"]
