[tox]
envlist = pylint, pep8, py39, py310, cover, bandit
minversion = 4.0.0
skipsdist = True
isolated_build = True

[testenv]
setenv =
    PYTHONPATH={toxinidir}
    PYTHONWARNINGS=default::DeprecationWarning
passenv = http_proxy,HTTP_PROXY,https_proxy,HTTPS_PROXY,no_proxy,NO_PROXY
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/test-requirements.txt
install_command = pip install {opts} {packages}
commands =
    python setup.py develop
    pytest --cov=qcos --cov-report=term-missing --cov-report=html tests/

[testenv:pylint]
basepython = python3.10
deps =
    pylint>=3.0.0
commands =
    python setup.py develop
    pylint --rcfile=.pylintrc qcos tests

[testenv:pep8]
basepython = python3.10
deps =
    pylint>=3.0.0
    flake8>=5.0.0
commands =
    python setup.py develop
    flake8 qcos tests
    pylint --rcfile=.pylintrc qcos tests

[testenv:py39]
basepython = python3.9
deps =
    {[testenv]deps}
commands =
    python setup.py develop
    pytest --cov=qcos --cov-report=term-missing --cov-report=html tests/

[testenv:py310]
basepython = python3.10
deps =
    {[testenv]deps}
commands =
    python setup.py develop
    pytest --cov=qcos --cov-report=term-missing --cov-report=html tests/

[testenv:cover]
basepython = python3.10
deps =
    {[testenv]deps}
commands =
    python setup.py develop
    pytest --cov=qcos --cov-report=term-missing --cov-report=html --cov-fail-under=80 tests/

[testenv:bandit]
basepython = python3.10
deps =
    bandit>=1.7.0
commands =
    python setup.py develop
    bandit -r qcos -x tests -n5