[log]
log_dir = runtime_log/qcos/
log_file_size = 10485760
log_file_count = 5

[openqasm]
original_openqasm_file_path = user_task/user_original_task
processing_openqasm_file_path = user_task/qcos_processing_task
qubit_nums = 10
shots_num = 1000
priority = 1
task_type = PriorityTask
task_result_path = task_result/xternal

[task]
fetch_interval = 60
sources = XTERNAL
fetch_task_num = 5
fetch_cancellation_task_num = 5
send_task_wait_time = 30
error_wait_time = 300
scheduler_wait_time = 30
max_concurrent_tasks = 5
task_aggregation_upper_threshold = 5
task_aggregation_lower_threshold = 2
task_aggregation_switch = false
collect_task_num = 1
single_gate_cost = 6E-6
multi_gate_cost = 2E-6

[qcos]
dqcos_url = http://127.0.0.1:5000
device_id = 1
autotest_url = http://100.78.61.1:8385

[AWG]
samplingRateMHz = 500
delay = 0
test_time = 0.5
awg_address = 192.168.1.1
channel = [1,2,3,4]
serialNumber = MY61390219
product = M3201A
amp = [0.2, 1.2, 0.4, 0.4]
#触发模式 0: 立即触发 2: 外部信号触发，实际实验中设置为2
trigger_mode = 2
awg_lib_path = C:/Program Files/Keysight/SD1/shared/SD1core
wave_id_file = ./wave_id.json
wave_file_dir = ./wave_file
# 执行模式 0：真机执行模式 1：调试模式
debug_mode = 1

[FPGA]
port = COM5
clock_period = 1E-3
test_time = 0.5
bytes_returned = 12
ext_trig = 1

[NI]
type = niao, nido, nidi
address = /dev1/ao0|/dev1/ao1|/dev1/ao4|/dev1/ao5|/dev1/ao6|/dev1/ao7|/dev1/ao8,
          /dev4/port0/line0:7|/dev4/port1/line1|/dev4/port1/line3:6|/dev4/port3/line6,
rate = 4e5, 5e5
trigger_source = /dev1/PFI0
delay_time = 0
delay_start = 0
# PGC冷却光作用时间
do0_pgc_cooling_time = 0
# 探测冷却光作用时间
do0_meas_cooling_time = 0
# PGC回泵光作用时间
do2_pgc_pump_time = 0
# 探测回泵光作用时间
do2_meas_pump_time = 0
# PGC冷却光失谐
ao1_pgc_cooling_detune = 3.2
# 探测冷却光失谐
ao1_meas_cooling_detune = 3.2
# 探测冷却光频率
ao1_meas_cooling_freq = 6.4
# PGC回泵光失谐
ao3_pgc_pump_detune = 3.4
# 探测回泵光失谐
ao3_meas_pump_detune = 4
# PGC水平补偿磁场
ao4_pgc_comp_mag = 1.277
# PGC阱方向补偿磁场
ao5_pgc_comp_mag = 1.261
# PGC上下补偿磁场
ao6_pgc_comp_mag = 1.325
# 拉曼Rabi实验中吸收峰
ao7_raman_source_freq = 1.325
# PGC回泵光幅度
ao8_pgc_pump_amp = 5
# 探测回泵光幅度
ao8_meas_pump_amp = 5
# PGC冷却光幅度
ao9_pgc_cooling_amp = 5

[topology]
topo_file = na_file.json

[execute]
qubit_number = 64
row_num = 8
col_num = 8
rea_region = [3, 5, 3, 5]
rea_dll_path = ./test.dll
raman_channel = [1, 2, 3, 4]
rea_channel = [1, 2]
rea_amp = [0.2, 1.2]

[measure]
calib_img_path = calib_img.png
quantum_task_res_img_path = quantum_task_res_img.png
; 量子比特状态的亮态阈值
threshold = 75
; 用于判断量子比特的有效像素点个数
threshold_block = 3
dll_path = D:/SourceCode/arclight/WuYueOs_Arclight/quantumOS/camera_test/lib/x64/TUCam.dll
init_path = D:/SourceCode/arclight/WuYueOs_Arclight/quantumOS/camera_test/
exposure_time = 50
width_offset = 975
height_offset = 700
roi_width = 232
roi_height = 232
total_width = 2048
total_height = 2048

[ising]
qubo_images_path = ising_response_result/qubo_images
zip_file_path = ising_response_result/result_files
ising_machine_ip = http://127.0.0.1:8088
