apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: prometheus
    access: proxy
    url: ${DATA_SOURCE}
    isDefault: true
    editable: true
    jsonData:
      timeInterval: "15s"
      httpMethod: POST
