[baihua_156]
alias_name = "百花 超导芯片 (Baihua)"
driver = "DriverBaihua"
description = "百花 超导芯片 (Baihua)"

[baihua_156.transpiler.qpu_configs]

qubits = 156

coupler_map.CZ0_1 = ['Q0', 'Q1']
coupler_map.CZ1_2 = ['Q1', 'Q2']
coupler_map.CZ2_3 = ['Q2', 'Q3']
coupler_map.CZ2_15 = ['Q2', 'Q15']
coupler_map.CZ3_4 = ['Q3', 'Q4']
coupler_map.CZ4_5 = ['Q4', 'Q5']
coupler_map.CZ5_6 = ['Q5', 'Q6']
coupler_map.CZ6_7 = ['Q6', 'Q7']
coupler_map.CZ6_19 = ['Q6', 'Q19']
coupler_map.CZ7_8 = ['Q7', 'Q8']
coupler_map.CZ8_9 = ['Q8', 'Q9']
coupler_map.CZ9_10 = ['Q9', 'Q10']
coupler_map.CZ10_11 = ['Q10', 'Q11']
coupler_map.CZ10_23 = ['Q10', 'Q23']
coupler_map.CZ11_12 = ['Q11', 'Q12']
coupler_map.CZ13_14 = ['Q13', 'Q14']
coupler_map.CZ13_26 = ['Q13', 'Q26']
coupler_map.CZ14_15 = ['Q14', 'Q15']
coupler_map.CZ15_16 = ['Q15', 'Q16']
coupler_map.CZ16_17 = ['Q16', 'Q17']
coupler_map.CZ17_18 = ['Q17', 'Q18']
coupler_map.CZ17_30 = ['Q17', 'Q30']
coupler_map.CZ18_19 = ['Q18', 'Q19']
coupler_map.CZ19_20 = ['Q19', 'Q20']
coupler_map.CZ20_21 = ['Q20', 'Q21']
coupler_map.CZ21_22 = ['Q21', 'Q22']
coupler_map.CZ21_34 = ['Q21', 'Q34']
coupler_map.CZ22_23 = ['Q22', 'Q23']
coupler_map.CZ23_24 = ['Q23', 'Q24']
coupler_map.CZ24_25 = ['Q24', 'Q25']
coupler_map.CZ25_38 = ['Q25', 'Q38']
coupler_map.CZ26_27 = ['Q26', 'Q27']
coupler_map.CZ27_28 = ['Q27', 'Q28']
coupler_map.CZ28_29 = ['Q28', 'Q29']
coupler_map.CZ28_41 = ['Q28', 'Q41']
coupler_map.CZ29_30 = ['Q29', 'Q30']
coupler_map.CZ30_31 = ['Q30', 'Q31']
coupler_map.CZ31_32 = ['Q31', 'Q32']
coupler_map.CZ32_33 = ['Q32', 'Q33']
coupler_map.CZ32_45 = ['Q32', 'Q45']
coupler_map.CZ33_34 = ['Q33', 'Q34']
coupler_map.CZ34_35 = ['Q34', 'Q35']
coupler_map.CZ35_36 = ['Q35', 'Q36']
coupler_map.CZ36_37 = ['Q36', 'Q37']
coupler_map.CZ36_49 = ['Q36', 'Q49']
coupler_map.CZ37_38 = ['Q37', 'Q38']
coupler_map.CZ39_40 = ['Q39', 'Q40']
coupler_map.CZ39_52 = ['Q39', 'Q52']
coupler_map.CZ40_41 = ['Q40', 'Q41']
coupler_map.CZ41_42 = ['Q41', 'Q42']
coupler_map.CZ42_43 = ['Q42', 'Q43']
coupler_map.CZ43_44 = ['Q43', 'Q44']
coupler_map.CZ43_56 = ['Q43', 'Q56']
coupler_map.CZ44_45 = ['Q44', 'Q45']
coupler_map.CZ45_46 = ['Q45', 'Q46']
coupler_map.CZ46_47 = ['Q46', 'Q47']
coupler_map.CZ47_48 = ['Q47', 'Q48']
coupler_map.CZ47_60 = ['Q47', 'Q60']
coupler_map.CZ48_49 = ['Q48', 'Q49']
coupler_map.CZ49_50 = ['Q49', 'Q50']
coupler_map.CZ50_51 = ['Q50', 'Q51']
coupler_map.CZ51_64 = ['Q51', 'Q64']
coupler_map.CZ52_53 = ['Q52', 'Q53']
coupler_map.CZ53_54 = ['Q53', 'Q54']
coupler_map.CZ54_55 = ['Q54', 'Q55']
coupler_map.CZ54_67 = ['Q54', 'Q67']
coupler_map.CZ55_56 = ['Q55', 'Q56']
coupler_map.CZ56_57 = ['Q56', 'Q57']
coupler_map.CZ57_58 = ['Q57', 'Q58']
coupler_map.CZ58_59 = ['Q58', 'Q59']
coupler_map.CZ58_71 = ['Q58', 'Q71']
coupler_map.CZ59_60 = ['Q59', 'Q60']
coupler_map.CZ60_61 = ['Q60', 'Q61']
coupler_map.CZ61_62 = ['Q61', 'Q62']
coupler_map.CZ62_63 = ['Q62', 'Q63']
coupler_map.CZ62_75 = ['Q62', 'Q75']
coupler_map.CZ63_64 = ['Q63', 'Q64']
coupler_map.CZ65_66 = ['Q65', 'Q66']
coupler_map.CZ65_78 = ['Q65', 'Q78']
coupler_map.CZ66_67 = ['Q66', 'Q67']
coupler_map.CZ67_68 = ['Q67', 'Q68']
coupler_map.CZ68_69 = ['Q68', 'Q69']
coupler_map.CZ69_70 = ['Q69', 'Q70']
coupler_map.CZ69_82 = ['Q69', 'Q82']
coupler_map.CZ70_71 = ['Q70', 'Q71']
coupler_map.CZ71_72 = ['Q71', 'Q72']
coupler_map.CZ72_73 = ['Q72', 'Q73']
coupler_map.CZ73_74 = ['Q73', 'Q74']
coupler_map.CZ73_86 = ['Q73', 'Q86']
coupler_map.CZ74_75 = ['Q74', 'Q75']
coupler_map.CZ75_76 = ['Q75', 'Q76']
coupler_map.CZ76_77 = ['Q76', 'Q77']
coupler_map.CZ77_90 = ['Q77', 'Q90']
coupler_map.CZ78_79 = ['Q78', 'Q79']
coupler_map.CZ79_80 = ['Q79', 'Q80']
coupler_map.CZ80_81 = ['Q80', 'Q81']
coupler_map.CZ80_93 = ['Q80', 'Q93']
coupler_map.CZ81_82 = ['Q81', 'Q82']
coupler_map.CZ82_83 = ['Q82', 'Q83']
coupler_map.CZ83_84 = ['Q83', 'Q84']
coupler_map.CZ84_85 = ['Q84', 'Q85']
coupler_map.CZ84_97 = ['Q84', 'Q97']
coupler_map.CZ85_86 = ['Q85', 'Q86']
coupler_map.CZ86_87 = ['Q86', 'Q87']
coupler_map.CZ87_88 = ['Q87', 'Q88']
coupler_map.CZ88_89 = ['Q88', 'Q89']
coupler_map.CZ88_101 = ['Q88', 'Q101']
coupler_map.CZ89_90 = ['Q89', 'Q90']
coupler_map.CZ91_92 = ['Q91', 'Q92']
coupler_map.CZ91_104 = ['Q91', 'Q104']
coupler_map.CZ92_93 = ['Q92', 'Q93']
coupler_map.CZ93_94 = ['Q93', 'Q94']
coupler_map.CZ94_95 = ['Q94', 'Q95']
coupler_map.CZ95_96 = ['Q95', 'Q96']
coupler_map.CZ95_108 = ['Q95', 'Q108']
coupler_map.CZ96_97 = ['Q96', 'Q97']
coupler_map.CZ97_98 = ['Q97', 'Q98']
coupler_map.CZ98_99 = ['Q98', 'Q99']
coupler_map.CZ99_100 = ['Q99', 'Q100']
coupler_map.CZ99_112 = ['Q99', 'Q112']
coupler_map.CZ100_101 = ['Q100', 'Q101']
coupler_map.CZ101_102 = ['Q101', 'Q102']
coupler_map.CZ102_103 = ['Q102', 'Q103']
coupler_map.CZ103_116 = ['Q103', 'Q116']
coupler_map.CZ104_105 = ['Q104', 'Q105']
coupler_map.CZ105_106 = ['Q105', 'Q106']
coupler_map.CZ106_107 = ['Q106', 'Q107']
coupler_map.CZ106_119 = ['Q106', 'Q119']
coupler_map.CZ107_108 = ['Q107', 'Q108']
coupler_map.CZ108_109 = ['Q108', 'Q109']
coupler_map.CZ109_110 = ['Q109', 'Q110']
coupler_map.CZ110_111 = ['Q110', 'Q111']
coupler_map.CZ110_123 = ['Q110', 'Q123']
coupler_map.CZ111_112 = ['Q111', 'Q112']
coupler_map.CZ112_113 = ['Q112', 'Q113']
coupler_map.CZ113_114 = ['Q113', 'Q114']
coupler_map.CZ114_115 = ['Q114', 'Q115']
coupler_map.CZ114_127 = ['Q114', 'Q127']
coupler_map.CZ115_116 = ['Q115', 'Q116']
coupler_map.CZ117_118 = ['Q117', 'Q118']
coupler_map.CZ117_130 = ['Q117', 'Q130']
coupler_map.CZ118_119 = ['Q118', 'Q119']
coupler_map.CZ119_120 = ['Q119', 'Q120']
coupler_map.CZ120_121 = ['Q120', 'Q121']
coupler_map.CZ121_122 = ['Q121', 'Q122']
coupler_map.CZ121_134 = ['Q121', 'Q134']
coupler_map.CZ122_123 = ['Q122', 'Q123']
coupler_map.CZ123_124 = ['Q123', 'Q124']
coupler_map.CZ124_125 = ['Q124', 'Q125']
coupler_map.CZ125_126 = ['Q125', 'Q126']
coupler_map.CZ125_138 = ['Q125', 'Q138']
coupler_map.CZ126_127 = ['Q126', 'Q127']
coupler_map.CZ127_128 = ['Q127', 'Q128']
coupler_map.CZ128_129 = ['Q128', 'Q129']
coupler_map.CZ129_142 = ['Q129', 'Q142']
coupler_map.CZ130_131 = ['Q130', 'Q131']
coupler_map.CZ131_132 = ['Q131', 'Q132']
coupler_map.CZ132_133 = ['Q132', 'Q133']
coupler_map.CZ132_145 = ['Q132', 'Q145']
coupler_map.CZ133_134 = ['Q133', 'Q134']
coupler_map.CZ134_135 = ['Q134', 'Q135']
coupler_map.CZ135_136 = ['Q135', 'Q136']
coupler_map.CZ136_137 = ['Q136', 'Q137']
coupler_map.CZ136_149 = ['Q136', 'Q149']
coupler_map.CZ137_138 = ['Q137', 'Q138']
coupler_map.CZ138_139 = ['Q138', 'Q139']
coupler_map.CZ139_140 = ['Q139', 'Q140']
coupler_map.CZ140_141 = ['Q140', 'Q141']
coupler_map.CZ140_153 = ['Q140', 'Q153']
coupler_map.CZ141_142 = ['Q141', 'Q142']
coupler_map.CZ143_144 = ['Q143', 'Q144']
coupler_map.CZ144_145 = ['Q144', 'Q145']
coupler_map.CZ145_146 = ['Q145', 'Q146']
coupler_map.CZ146_147 = ['Q146', 'Q147']
coupler_map.CZ147_148 = ['Q147', 'Q148']
coupler_map.CZ148_149 = ['Q148', 'Q149']
coupler_map.CZ149_150 = ['Q149', 'Q150']
coupler_map.CZ150_151 = ['Q150', 'Q151']
coupler_map.CZ151_152 = ['Q151', 'Q152']
coupler_map.CZ152_153 = ['Q152', 'Q153']
coupler_map.CZ153_154 = ['Q153', 'Q154']
coupler_map.CZ154_155 = ['Q154', 'Q155']

readout_error.Q0 = 0.001
readout_error.Q1 = 0.006
readout_error.Q2 = 0.002
readout_error.Q3 = 0.016
readout_error.Q4 = 0.001
readout_error.Q5 = 0.001
readout_error.Q6 = 0.003
readout_error.Q7 = 0.001
readout_error.Q8 = 0.02
readout_error.Q9 = 0.001
readout_error.Q10 = 0.001
readout_error.Q11 = 0.001
readout_error.Q12 = 0.001
readout_error.Q13 = 0.012
readout_error.Q14 = 0.001
readout_error.Q15 = 0.027
readout_error.Q16 = 0.001
readout_error.Q17 = 0.001
readout_error.Q18 = 0.004
readout_error.Q19 = 0.001
readout_error.Q20 = 0.001
readout_error.Q21 = 0.002
readout_error.Q22 = 0.001
readout_error.Q23 = 0.003
readout_error.Q24 = 0.001
readout_error.Q25 = 0.001
readout_error.Q26 = 0.004
readout_error.Q27 = 0.001
readout_error.Q28 = 0.001
readout_error.Q29 = 0.001
readout_error.Q30 = 0.001
readout_error.Q31 = 0.033
readout_error.Q32 = 0.001
readout_error.Q33 = 0.001
readout_error.Q34 = 0.001
readout_error.Q35 = 0.02
readout_error.Q36 = 0.003
readout_error.Q37 = 0.002
readout_error.Q38 = 0.001
readout_error.Q39 = 0.001
readout_error.Q40 = 0.002
readout_error.Q41 = 0.002
readout_error.Q42 = 0.001
readout_error.Q43 = 0.001
readout_error.Q44 = 0.001
readout_error.Q45 = 0.001
readout_error.Q46 = 0.001
readout_error.Q47 = 0.001
readout_error.Q48 = 0.001
readout_error.Q49 = 0.001
readout_error.Q50 = 0.071
readout_error.Q51 = 0.001
readout_error.Q52 = 0.001
readout_error.Q53 = 0.001
readout_error.Q54 = 0.001
readout_error.Q55 = 0.007
readout_error.Q56 = 1
readout_error.Q57 = 0.001
readout_error.Q58 = 0.001
readout_error.Q59 = 0.002
readout_error.Q60 = 0.001
readout_error.Q61 = 0.001
readout_error.Q62 = 0.001
readout_error.Q63 = 0.002
readout_error.Q64 = 0.001
readout_error.Q65 = 0.003
readout_error.Q66 = 1
readout_error.Q67 = 0.002
readout_error.Q68 = 0.001
readout_error.Q69 = 0.001
readout_error.Q70 = 0.003
readout_error.Q71 = 0.001
readout_error.Q72 = 0.001
readout_error.Q73 = 0.001
readout_error.Q74 = 0.003
readout_error.Q75 = 0.002
readout_error.Q76 = 0.001
readout_error.Q77 = 0.001
readout_error.Q78 = 0.001
readout_error.Q79 = 0.004
readout_error.Q80 = 0.001
readout_error.Q81 = 0.001
readout_error.Q82 = 0.001
readout_error.Q83 = 0.001
readout_error.Q84 = 0.002
readout_error.Q85 = 0.009
readout_error.Q86 = 0.002
readout_error.Q87 = 0.001
readout_error.Q88 = 0.001
readout_error.Q89 = 0.001
readout_error.Q90 = 0.001
readout_error.Q91 = 0.001
readout_error.Q92 = 0.001
readout_error.Q93 = 0.001
readout_error.Q94 = 0.001
readout_error.Q95 = 0.001
readout_error.Q96 = 0.017
readout_error.Q97 = 0.001
readout_error.Q98 = 0.001
readout_error.Q99 = 0.001
readout_error.Q100 = 0.001
readout_error.Q101 = 0.006
readout_error.Q102 = 0.001
readout_error.Q103 = 0.001
readout_error.Q104 = 0.002
readout_error.Q105 = 0.001
readout_error.Q106 = 0.001
readout_error.Q107 = 0.001
readout_error.Q108 = 0.002
readout_error.Q109 = 0.001
readout_error.Q110 = 0.005
readout_error.Q111 = 1
readout_error.Q112 = 0.002
readout_error.Q113 = 0.001
readout_error.Q114 = 0.001
readout_error.Q115 = 0.002
readout_error.Q116 = 0.001
readout_error.Q117 = 0.001
readout_error.Q118 = 0.001
readout_error.Q119 = 0.002
readout_error.Q120 = 0.002
readout_error.Q121 = 0.001
readout_error.Q122 = 0.001
readout_error.Q123 = 0.002
readout_error.Q124 = 0.003
readout_error.Q125 = 0.002
readout_error.Q126 = 0.005
readout_error.Q127 = 0.002
readout_error.Q128 = 0.001
readout_error.Q129 = 0.002
readout_error.Q130 = 0.001
readout_error.Q131 = 1
readout_error.Q132 = 0.001
readout_error.Q133 = 0.003
readout_error.Q134 = 0.001
readout_error.Q135 = 0.001
readout_error.Q136 = 0.001
readout_error.Q137 = 0.001
readout_error.Q138 = 0.002
readout_error.Q139 = 0.001
readout_error.Q140 = 0.001
readout_error.Q141 = 0.001
readout_error.Q142 = 0.001
readout_error.Q143 = 0.001
readout_error.Q144 = 0.001
readout_error.Q145 = 0.001
readout_error.Q146 = 0.001
readout_error.Q147 = 0.001
readout_error.Q148 = 0.001
readout_error.Q149 = 0.001
readout_error.Q150 = 0.001
readout_error.Q151 = 0.001
readout_error.Q152 = 0.001
readout_error.Q153 = 0.05
readout_error.Q154 = 0.001
readout_error.Q155 = 0.001

coupler_error.CZ0_1 = 1
coupler_error.CZ1_2 = 1
coupler_error.CZ2_3 = 0.014
coupler_error.CZ2_15 = 0.014
coupler_error.CZ3_4 = 0.024
coupler_error.CZ4_5 = 1
coupler_error.CZ5_6 = 1
coupler_error.CZ6_7 = 0.016
coupler_error.CZ6_19 = 1
coupler_error.CZ7_8 = 1
coupler_error.CZ8_9 = 1
coupler_error.CZ9_10 = 0.011
coupler_error.CZ10_11 = 1
coupler_error.CZ10_23 = 0.027
coupler_error.CZ11_12 = 1
coupler_error.CZ13_14 = 1
coupler_error.CZ13_26 = 0.03
coupler_error.CZ14_15 = 0.007
coupler_error.CZ15_16 = 1
coupler_error.CZ16_17 = 0.01
coupler_error.CZ17_18 = 1
coupler_error.CZ17_30 = 0.02
coupler_error.CZ18_19 = 1
coupler_error.CZ19_20 = 1
coupler_error.CZ20_21 = 1
coupler_error.CZ21_22 = 0.014
coupler_error.CZ21_34 = 0.03
coupler_error.CZ22_23 = 0.015
coupler_error.CZ23_24 = 0.031
coupler_error.CZ24_25 = 1
coupler_error.CZ25_38 = 0.016
coupler_error.CZ26_27 = 1
coupler_error.CZ27_28 = 1
coupler_error.CZ28_29 = 0.01
coupler_error.CZ28_41 = 0.014
coupler_error.CZ29_30 = 1
coupler_error.CZ30_31 = 0.021
coupler_error.CZ31_32 = 1
coupler_error.CZ32_33 = 0.01
coupler_error.CZ32_45 = 0.011
coupler_error.CZ33_34 = 0.013
coupler_error.CZ34_35 = 1
coupler_error.CZ35_36 = 1
coupler_error.CZ36_37 = 0.05
coupler_error.CZ36_49 = 1
coupler_error.CZ37_38 = 1
coupler_error.CZ39_40 = 0.011
coupler_error.CZ39_52 = 0.017
coupler_error.CZ40_41 = 0.012
coupler_error.CZ41_42 = 0.011
coupler_error.CZ42_43 = 0.006
coupler_error.CZ43_44 = 0.01
coupler_error.CZ43_56 = 1
coupler_error.CZ44_45 = 0.01
coupler_error.CZ45_46 = 0.045
coupler_error.CZ46_47 = 0.014
coupler_error.CZ47_48 = 0.01
coupler_error.CZ47_60 = 0.022
coupler_error.CZ48_49 = 1
coupler_error.CZ49_50 = 1
coupler_error.CZ50_51 = 1
coupler_error.CZ51_64 = 1
coupler_error.CZ52_53 = 0.012
coupler_error.CZ53_54 = 1
coupler_error.CZ54_55 = 1
coupler_error.CZ54_67 = 0.015
coupler_error.CZ55_56 = 1
coupler_error.CZ56_57 = 1
coupler_error.CZ57_58 = 1
coupler_error.CZ58_59 = 0.011
coupler_error.CZ58_71 = 1
coupler_error.CZ59_60 = 0.043
coupler_error.CZ60_61 = 1
coupler_error.CZ61_62 = 1
coupler_error.CZ62_63 = 1
coupler_error.CZ62_75 = 0.02
coupler_error.CZ63_64 = 1
coupler_error.CZ65_66 = 1
coupler_error.CZ65_78 = 0.03
coupler_error.CZ66_67 = 1
coupler_error.CZ67_68 = 1
coupler_error.CZ68_69 = 0.005
coupler_error.CZ69_70 = 0.009
coupler_error.CZ69_82 = 0.021
coupler_error.CZ70_71 = 0.037
coupler_error.CZ71_72 = 0.03
coupler_error.CZ72_73 = 0.04
coupler_error.CZ73_74 = 0.005
coupler_error.CZ73_86 = 1
coupler_error.CZ74_75 = 1
coupler_error.CZ75_76 = 0.013
coupler_error.CZ76_77 = 0.007
coupler_error.CZ77_90 = 0.009
coupler_error.CZ78_79 = 0.014
coupler_error.CZ79_80 = 0.012
coupler_error.CZ80_81 = 0.007
coupler_error.CZ80_93 = 1
coupler_error.CZ81_82 = 0.011
coupler_error.CZ82_83 = 0.05
coupler_error.CZ83_84 = 0.02
coupler_error.CZ84_85 = 0.012
coupler_error.CZ84_97 = 1
coupler_error.CZ85_86 = 0.025
coupler_error.CZ86_87 = 0.01
coupler_error.CZ87_88 = 1
coupler_error.CZ88_89 = 1
coupler_error.CZ88_101 = 1
coupler_error.CZ89_90 = 0.009
coupler_error.CZ91_92 = 0.013
coupler_error.CZ91_104 = 0.03
coupler_error.CZ92_93 = 0.013
coupler_error.CZ93_94 = 0.07
coupler_error.CZ94_95 = 0.006
coupler_error.CZ95_96 = 1
coupler_error.CZ95_108 = 0.049
coupler_error.CZ96_97 = 1
coupler_error.CZ97_98 = 0.007
coupler_error.CZ98_99 = 0.014
coupler_error.CZ99_100 = 0.02
coupler_error.CZ99_112 = 1
coupler_error.CZ100_101 = 1
coupler_error.CZ101_102 = 0.012
coupler_error.CZ102_103 = 0.022
coupler_error.CZ103_116 = 1
coupler_error.CZ104_105 = 0.1
coupler_error.CZ105_106 = 0.011
coupler_error.CZ106_107 = 0.043
coupler_error.CZ106_119 = 0.1
coupler_error.CZ107_108 = 1
coupler_error.CZ108_109 = 0.03
coupler_error.CZ109_110 = 0.016
coupler_error.CZ110_111 = 1
coupler_error.CZ110_123 = 0.06
coupler_error.CZ111_112 = 1
coupler_error.CZ112_113 = 1
coupler_error.CZ113_114 = 1
coupler_error.CZ114_115 = 1
coupler_error.CZ114_127 = 0.04
coupler_error.CZ115_116 = 1
coupler_error.CZ117_118 = 0.013
coupler_error.CZ117_130 = 0.012
coupler_error.CZ118_119 = 1
coupler_error.CZ119_120 = 0.055
coupler_error.CZ120_121 = 0.011
coupler_error.CZ121_122 = 0.067
coupler_error.CZ121_134 = 1
coupler_error.CZ122_123 = 0.071
coupler_error.CZ123_124 = 1
coupler_error.CZ124_125 = 1
coupler_error.CZ125_126 = 0.1
coupler_error.CZ125_138 = 0.04
coupler_error.CZ126_127 = 1
coupler_error.CZ127_128 = 0.029
coupler_error.CZ128_129 = 1
coupler_error.CZ129_142 = 1
coupler_error.CZ130_131 = 1
coupler_error.CZ131_132 = 1
coupler_error.CZ132_133 = 1
coupler_error.CZ132_145 = 0.049
coupler_error.CZ133_134 = 0.1
coupler_error.CZ134_135 = 1
coupler_error.CZ135_136 = 1
coupler_error.CZ136_137 = 0.01
coupler_error.CZ136_149 = 0.03
coupler_error.CZ137_138 = 0.023
coupler_error.CZ138_139 = 0.03
coupler_error.CZ139_140 = 1
coupler_error.CZ140_141 = 0.05
coupler_error.CZ140_153 = 0.06
coupler_error.CZ141_142 = 0.018
coupler_error.CZ143_144 = 0.02
coupler_error.CZ144_145 = 0.03
coupler_error.CZ145_146 = 1
coupler_error.CZ146_147 = 1
coupler_error.CZ147_148 = 0.03
coupler_error.CZ148_149 = 1
coupler_error.CZ149_150 = 1
coupler_error.CZ150_151 = 0.04
coupler_error.CZ151_152 = 0.03
coupler_error.CZ152_153 = 1
coupler_error.CZ153_154 = 0.029
coupler_error.CZ154_155 = 0.02
