[hanyuan1]
alias_name = "中科酷原-汉原1-120"
driver = "DriverHanyuan1-120"
description = "中科酷原-汉原120比特模拟测试脚本"

[hanyuan1.transpiler.qpu_configs]
qubits = 120
storage_area = ["S0", "S1", "S2", "S3", "S4", "S5", "S6", "S7", "S8", "S9",
                "S10", "S11", "S12", "S13", "S14", "S15", "S16", "S17", "S18", "S19",
                "S20", "S21", "S22", "S23", "S24", "S25", "S26", "S27", "S28", "S29",
                "S30", "S31", "S32", "S33", "S34", "S35", "S36", "S37", "S38", "S39",
                "S40", "S41", "S42", "S43", "S44", "S45", "S46", "S47", "S48", "S49",
                "S50", "S51", "S52", "S53", "S54", "S55", "S56", "S57", "S58", "S59",
                "S60", "S61", "S62", "S63", "S64", "S65", "S66", "S67", "S68", "S69",
                "S70", "S71", "S72", "S73", "S74", "S75", "S76", "S77", "S78", "S79",
                "S80", "S81", "S82", "S83", "S84", "S85", "S86", "S87", "S88", "S89",
                "S90", "S91", "S92", "S93", "S94", "S95", "S96", "S97", "S98", "S99",
                "S100", "S101", "S102", "S103", "S104", "S105", "S106", "S107", "S108", "S109",
                "S110", "S111", "S112", "S113", "S114", "S115", "S116", "S117", "S118", "S119"]
operate_area = ["P0", "P1", "P2", "P3", "P4", "P5", "P6", "P7", "P8", "P9",
                "P10", "P11", "P12", "P13", "P14", "P15", "P16", "P17", "P18", "P19",
                "P20", "P21", "P22", "P23", "P24", "P25", "P26", "P27", "P28", "P29",
                "P30", "P31", "P32", "P33", "P34", "P35", "P36", "P37", "P38", "P39",
                "P40", "P41", "P42", "P43", "P44", "P45", "P46", "P47", "P48", "P49",
                "P50", "P51", "P52", "P53", "P54", "P55", "P56", "P57", "P58", "P59",
                "P60", "P61", "P62", "P63", "P64", "P65", "P66", "P67", "P68", "P69",
                "P70", "P71", "P72", "P73", "P74", "P75", "P76", "P77", "P78", "P79",
                "P80", "P81", "P82", "P83", "P84", "P85", "P86", "P87", "P88", "P89",
                "P90", "P91", "P92", "P93", "P94", "P95", "P96", "P97", "P98", "P99",
                "P100", "P101", "P102", "P103", "P104", "P105", "P106", "P107", "P108", "P109",
                "P110", "P111", "P112", "P113", "P114", "P115", "P116", "P117", "P118", "P119"]

coupler_map.G0 = ["P0", "P1"]
coupler_map.G1 = ["P1", "P2"]
coupler_map.G2 = ["P2", "P3"]
coupler_map.G3 = ["P3", "P4"]
coupler_map.G4 = ["P4", "P5"]
coupler_map.G5 = ["P5", "P6"]
coupler_map.G6 = ["P6", "P7"]
coupler_map.G7 = ["P7", "P8"]
coupler_map.G8 = ["P8", "P9"]
coupler_map.G9 = ["P10", "P11"]
coupler_map.G10 = ["P11", "P12"]
coupler_map.G11 = ["P12", "P13"]
coupler_map.G12 = ["P13", "P14"]
coupler_map.G13 = ["P14", "P15"]
coupler_map.G14 = ["P15", "P16"]
coupler_map.G15 = ["P16", "P17"]
coupler_map.G16 = ["P17", "P18"]
coupler_map.G17 = ["P18", "P19"]
coupler_map.G18 = ["P20", "P21"]
coupler_map.G19 = ["P21", "P22"]
coupler_map.G20 = ["P22", "P23"]
coupler_map.G21 = ["P23", "P24"]
coupler_map.G22 = ["P24", "P25"]
coupler_map.G23 = ["P25", "P26"]
coupler_map.G24 = ["P26", "P27"]
coupler_map.G25 = ["P27", "P28"]
coupler_map.G26 = ["P28", "P29"]
coupler_map.G27 = ["P30", "P31"]
coupler_map.G28 = ["P31", "P32"]
coupler_map.G29 = ["P32", "P33"]
coupler_map.G30 = ["P33", "P34"]
coupler_map.G31 = ["P34", "P35"]
coupler_map.G32 = ["P35", "P36"]
coupler_map.G33 = ["P36", "P37"]
coupler_map.G34 = ["P37", "P38"]
coupler_map.G35 = ["P38", "P39"]
coupler_map.G36 = ["P40", "P41"]
coupler_map.G37 = ["P41", "P42"]
coupler_map.G38 = ["P42", "P43"]
coupler_map.G39 = ["P43", "P44"]
coupler_map.G40 = ["P44", "P45"]
coupler_map.G41 = ["P45", "P46"]
coupler_map.G42 = ["P46", "P47"]
coupler_map.G43 = ["P47", "P48"]
coupler_map.G44 = ["P48", "P49"]
coupler_map.G45 = ["P50", "P51"]
coupler_map.G46 = ["P51", "P52"]
coupler_map.G47 = ["P52", "P53"]
coupler_map.G48 = ["P53", "P54"]
coupler_map.G49 = ["P54", "P55"]
coupler_map.G50 = ["P55", "P56"]
coupler_map.G51 = ["P56", "P57"]
coupler_map.G52 = ["P57", "P58"]
coupler_map.G53 = ["P58", "P59"]
coupler_map.G54 = ["P60", "P61"]
coupler_map.G55 = ["P61", "P62"]
coupler_map.G56 = ["P62", "P63"]
coupler_map.G57 = ["P63", "P64"]
coupler_map.G58 = ["P64", "P65"]
coupler_map.G59 = ["P65", "P66"]
coupler_map.G60 = ["P66", "P67"]
coupler_map.G61 = ["P67", "P68"]
coupler_map.G62 = ["P68", "P69"]
coupler_map.G63 = ["P70", "P71"]
coupler_map.G64 = ["P71", "P72"]
coupler_map.G65 = ["P72", "P73"]
coupler_map.G66 = ["P73", "P74"]
coupler_map.G67 = ["P74", "P75"]
coupler_map.G68 = ["P75", "P76"]
coupler_map.G69 = ["P76", "P77"]
coupler_map.G70 = ["P77", "P78"]
coupler_map.G71 = ["P78", "P79"]
coupler_map.G72 = ["P80", "P81"]
coupler_map.G73 = ["P81", "P82"]
coupler_map.G74 = ["P82", "P83"]
coupler_map.G75 = ["P83", "P84"]
coupler_map.G76 = ["P84", "P85"]
coupler_map.G77 = ["P85", "P86"]
coupler_map.G78 = ["P86", "P87"]
coupler_map.G79 = ["P87", "P88"]
coupler_map.G80 = ["P88", "P89"]
coupler_map.G81 = ["P90", "P91"]
coupler_map.G82 = ["P91", "P92"]
coupler_map.G83 = ["P92", "P93"]
coupler_map.G84 = ["P93", "P94"]
coupler_map.G85 = ["P94", "P95"]
coupler_map.G86 = ["P95", "P96"]
coupler_map.G87 = ["P96", "P97"]
coupler_map.G88 = ["P97", "P98"]
coupler_map.G89 = ["P98", "P99"]
coupler_map.G90 = ["P100", "P101"]
coupler_map.G91 = ["P101", "P102"]
coupler_map.G92 = ["P102", "P103"]
coupler_map.G93 = ["P103", "P104"]
coupler_map.G94 = ["P104", "P105"]
coupler_map.G95 = ["P105", "P106"]
coupler_map.G96 = ["P106", "P107"]
coupler_map.G97 = ["P107", "P108"]
coupler_map.G98 = ["P108", "P109"]
coupler_map.G99 = ["P110", "P111"]
coupler_map.G100 = ["P111", "P112"]
coupler_map.G101 = ["P112", "P113"]
coupler_map.G102 = ["P113", "P114"]
coupler_map.G103 = ["P114", "P115"]
coupler_map.G104 = ["P115", "P116"]
coupler_map.G105 = ["P116", "P117"]
coupler_map.G106 = ["P117", "P118"]
coupler_map.G107 = ["P118", "P119"]
coupler_map.G108 = ["P0", "P10"]
coupler_map.G109 = ["P10", "P20"]
coupler_map.G110 = ["P20", "P30"]
coupler_map.G111 = ["P30", "P40"]
coupler_map.G112 = ["P40", "P50"]
coupler_map.G113 = ["P50", "P60"]
coupler_map.G114 = ["P60", "P70"]
coupler_map.G115 = ["P70", "P80"]
coupler_map.G116 = ["P80", "P90"]
coupler_map.G117 = ["P90", "P100"]
coupler_map.G118 = ["P100", "P110"]
coupler_map.G119 = ["P1", "P11"]
coupler_map.G120 = ["P11", "P21"]
coupler_map.G121 = ["P21", "P31"]
coupler_map.G122 = ["P31", "P41"]
coupler_map.G123 = ["P41", "P51"]
coupler_map.G124 = ["P51", "P61"]
coupler_map.G125 = ["P61", "P71"]
coupler_map.G126 = ["P71", "P81"]
coupler_map.G127 = ["P81", "P91"]
coupler_map.G128 = ["P91", "P101"]
coupler_map.G129 = ["P101", "P111"]
coupler_map.G130 = ["P2", "P12"]
coupler_map.G131 = ["P12", "P22"]
coupler_map.G132 = ["P22", "P32"]
coupler_map.G133 = ["P32", "P42"]
coupler_map.G134 = ["P42", "P52"]
coupler_map.G135 = ["P52", "P62"]
coupler_map.G136 = ["P62", "P72"]
coupler_map.G137 = ["P72", "P82"]
coupler_map.G138 = ["P82", "P92"]
coupler_map.G139 = ["P92", "P102"]
coupler_map.G140 = ["P102", "P112"]
coupler_map.G141 = ["P3", "P13"]
coupler_map.G142 = ["P13", "P23"]
coupler_map.G143 = ["P23", "P33"]
coupler_map.G144 = ["P33", "P43"]
coupler_map.G145 = ["P43", "P53"]
coupler_map.G146 = ["P53", "P63"]
coupler_map.G147 = ["P63", "P73"]
coupler_map.G148 = ["P73", "P83"]
coupler_map.G149 = ["P83", "P93"]
coupler_map.G150 = ["P93", "P103"]
coupler_map.G151 = ["P103", "P113"]
coupler_map.G152 = ["P4", "P14"]
coupler_map.G153 = ["P14", "P24"]
coupler_map.G154 = ["P24", "P34"]
coupler_map.G155 = ["P34", "P44"]
coupler_map.G156 = ["P44", "P54"]
coupler_map.G157 = ["P54", "P64"]
coupler_map.G158 = ["P64", "P74"]
coupler_map.G159 = ["P74", "P84"]
coupler_map.G160 = ["P84", "P94"]
coupler_map.G161 = ["P94", "P104"]
coupler_map.G162 = ["P104", "P114"]
coupler_map.G163 = ["P5", "P15"]
coupler_map.G164 = ["P15", "P25"]
coupler_map.G165 = ["P25", "P35"]
coupler_map.G166 = ["P35", "P45"]
coupler_map.G167 = ["P45", "P55"]
coupler_map.G168 = ["P55", "P65"]
coupler_map.G169 = ["P65", "P75"]
coupler_map.G170 = ["P75", "P85"]
coupler_map.G171 = ["P85", "P95"]
coupler_map.G172 = ["P95", "P105"]
coupler_map.G173 = ["P105", "P115"]
coupler_map.G174 = ["P6", "P16"]
coupler_map.G175 = ["P16", "P26"]
coupler_map.G176 = ["P26", "P36"]
coupler_map.G177 = ["P36", "P46"]
coupler_map.G178 = ["P46", "P56"]
coupler_map.G179 = ["P56", "P66"]
coupler_map.G180 = ["P66", "P76"]
coupler_map.G181 = ["P76", "P86"]
coupler_map.G182 = ["P86", "P96"]
coupler_map.G183 = ["P96", "P106"]
coupler_map.G184 = ["P106", "P116"]
coupler_map.G185 = ["P7", "P17"]
coupler_map.G186 = ["P17", "P27"]
coupler_map.G187 = ["P27", "P37"]
coupler_map.G188 = ["P37", "P47"]
coupler_map.G189 = ["P47", "P57"]
coupler_map.G190 = ["P57", "P67"]
coupler_map.G191 = ["P67", "P77"]
coupler_map.G192 = ["P77", "P87"]
coupler_map.G193 = ["P87", "P97"]
coupler_map.G194 = ["P97", "P107"]
coupler_map.G195 = ["P107", "P117"]
coupler_map.G196 = ["P8", "P18"]
coupler_map.G197 = ["P18", "P28"]
coupler_map.G198 = ["P28", "P38"]
coupler_map.G199 = ["P38", "P48"]
coupler_map.G200 = ["P48", "P58"]
coupler_map.G201 = ["P58", "P68"]
coupler_map.G202 = ["P68", "P78"]
coupler_map.G203 = ["P78", "P88"]
coupler_map.G204 = ["P88", "P98"]
coupler_map.G205 = ["P98", "P108"]
coupler_map.G206 = ["P108", "P118"]
coupler_map.G207 = ["P9", "P19"]
coupler_map.G208 = ["P19", "P29"]
coupler_map.G209 = ["P29", "P39"]
coupler_map.G210 = ["P39", "P49"]
coupler_map.G211 = ["P49", "P59"]
coupler_map.G212 = ["P59", "P69"]
coupler_map.G213 = ["P69", "P79"]
coupler_map.G214 = ["P79", "P89"]
coupler_map.G215 = ["P89", "P99"]
coupler_map.G216 = ["P99", "P109"]
coupler_map.G217 = ["P109", "P119"]

readout_error.S0 = 0.5
readout_error.S1 = 0.6
readout_error.S2 = 0.7
readout_error.S3 = 0.8
readout_error.S4 = 0.9
readout_error.S5 = 1.0
readout_error.S6 = 1.1
readout_error.S7 = 1.2
readout_error.S8 = 1.3
readout_error.S9 = 1.4
readout_error.S10 = 1.5
readout_error.S11 = 1.6
readout_error.S12 = 1.7
readout_error.S13 = 1.8
readout_error.S14 = 1.9
readout_error.S15 = 2.0
readout_error.S16 = 2.1
readout_error.S17 = 2.2
readout_error.S18 = 2.3
readout_error.S19 = 2.4
readout_error.S20 = 2.5
readout_error.S21 = 2.6
readout_error.S22 = 2.7
readout_error.S23 = 2.8
readout_error.S24 = 2.9
readout_error.S25 = 3.0
readout_error.S26 = 3.1
readout_error.S27 = 3.2
readout_error.S28 = 3.3
readout_error.S29 = 3.4
readout_error.S30 = 3.5
readout_error.S31 = 3.6
readout_error.S32 = 3.7
readout_error.S33 = 3.8
readout_error.S34 = 3.9
readout_error.S35 = 4.0
readout_error.S36 = 4.1
readout_error.S37 = 4.2
readout_error.S38 = 4.3
readout_error.S39 = 4.4
readout_error.S40 = 4.5
readout_error.S41 = 4.6
readout_error.S42 = 4.7
readout_error.S43 = 4.8
readout_error.S44 = 4.9
readout_error.S45 = 5.0
readout_error.S46 = 5.1
readout_error.S47 = 5.2
readout_error.S48 = 5.3
readout_error.S49 = 5.4
readout_error.S50 = 5.5
readout_error.S51 = 5.6
readout_error.S52 = 5.7
readout_error.S53 = 5.8
readout_error.S54 = 5.9
readout_error.S55 = 6.0
readout_error.S56 = 6.1
readout_error.S57 = 6.2
readout_error.S58 = 6.3
readout_error.S59 = 6.4
readout_error.S60 = 6.5
readout_error.S61 = 6.6
readout_error.S62 = 6.7
readout_error.S63 = 6.8
readout_error.S64 = 6.9
readout_error.S65 = 7.0
readout_error.S66 = 7.1
readout_error.S67 = 7.2
readout_error.S68 = 7.3
readout_error.S69 = 7.4
readout_error.S70 = 7.5
readout_error.S71 = 7.6
readout_error.S72 = 7.7
readout_error.S73 = 7.8
readout_error.S74 = 7.9
readout_error.S75 = 8.0
readout_error.S76 = 8.1
readout_error.S77 = 8.2
readout_error.S78 = 8.3
readout_error.S79 = 8.4
readout_error.S80 = 8.5
readout_error.S81 = 8.6
readout_error.S82 = 8.7
readout_error.S83 = 8.8
readout_error.S84 = 8.9
readout_error.S85 = 9.0
readout_error.S86 = 9.1
readout_error.S87 = 9.2
readout_error.S88 = 9.3
readout_error.S89 = 9.4
readout_error.S90 = 9.5
readout_error.S91 = 9.6
readout_error.S92 = 9.7
readout_error.S93 = 9.8
readout_error.S94 = 9.9
readout_error.S95 = 10.0
readout_error.S96 = 10.1
readout_error.S97 = 10.2
readout_error.S98 = 10.3
readout_error.S99 = 10.4
readout_error.S100 = 10.5
readout_error.S101 = 10.6
readout_error.S102 = 10.7
readout_error.S103 = 10.8
readout_error.S104 = 10.9
readout_error.S105 = 11.0
readout_error.S106 = 11.1
readout_error.S107 = 11.2
readout_error.S108 = 11.3
readout_error.S109 = 11.4
readout_error.S110 = 11.5
readout_error.S111 = 11.6
readout_error.S112 = 11.7
readout_error.S113 = 11.8
readout_error.S114 = 11.9
readout_error.S115 = 12.0
readout_error.S116 = 12.1
readout_error.S117 = 12.2
readout_error.S118 = 12.3
readout_error.S119 = 12.4

coupler_error.G0 = 1.0
coupler_error.G1 = 1.1
coupler_error.G2 = 1.2
coupler_error.G3 = 1.3
coupler_error.G4 = 1.4
coupler_error.G5 = 1.5
coupler_error.G6 = 1.6
coupler_error.G7 = 1.7
coupler_error.G8 = 1.8
coupler_error.G9 = 1.9
coupler_error.G10 = 2.0
coupler_error.G11 = 2.1
coupler_error.G12 = 2.2
coupler_error.G13 = 2.3
coupler_error.G14 = 2.4
coupler_error.G15 = 2.5
coupler_error.G16 = 2.6
coupler_error.G17 = 2.7
coupler_error.G18 = 2.8
coupler_error.G19 = 2.9
coupler_error.G20 = 3.0
coupler_error.G21 = 3.1
coupler_error.G22 = 3.2
coupler_error.G23 = 3.3
coupler_error.G24 = 3.4
coupler_error.G25 = 3.5
coupler_error.G26 = 3.6
coupler_error.G27 = 3.7
coupler_error.G28 = 3.8
coupler_error.G29 = 3.9
coupler_error.G30 = 4.0
coupler_error.G31 = 4.1
coupler_error.G32 = 4.2
coupler_error.G33 = 4.3
coupler_error.G34 = 4.4
coupler_error.G35 = 4.5
coupler_error.G36 = 4.6
coupler_error.G37 = 4.7
coupler_error.G38 = 4.8
coupler_error.G39 = 4.9
coupler_error.G40 = 5.0
coupler_error.G41 = 5.1
coupler_error.G42 = 5.2
coupler_error.G43 = 5.3
coupler_error.G44 = 5.4
coupler_error.G45 = 5.5
coupler_error.G46 = 5.6
coupler_error.G47 = 5.7
coupler_error.G48 = 5.8
coupler_error.G49 = 5.9
coupler_error.G50 = 6.0
coupler_error.G51 = 6.1

closest.P0 = "S0"
closest.P1 = "S1"
closest.P2 = "S2"
closest.P3 = "S3"
closest.P4 = "S4"
closest.P5 = "S5"
closest.P6 = "S6"
closest.P7 = "S7"
closest.P8 = "S8"
closest.P9 = "S9"
closest.P10 = "S10"
closest.P11 = "S11"
closest.P12 = "S12"
closest.P13 = "S13"
closest.P14 = "S14"
closest.P15 = "S15"
closest.P16 = "S16"
closest.P17 = "S17"
closest.P18 = "S18"
closest.P19 = "S19"
closest.P20 = "S20"
closest.P21 = "S21"
closest.P22 = "S22"
closest.P23 = "S23"
closest.P24 = "S24"
closest.P25 = "S25"
closest.P26 = "S26"
closest.P27 = "S27"
closest.P28 = "S28"
closest.P29 = "S29"
closest.P30 = "S30"
closest.P31 = "S31"
closest.P32 = "S32"
closest.P33 = "S33"
closest.P34 = "S34"
closest.P35 = "S35"
closest.P36 = "S36"
closest.P37 = "S37"
closest.P38 = "S38"
closest.P39 = "S39"
closest.P40 = "S40"
closest.P41 = "S41"
closest.P42 = "S42"
closest.P43 = "S43"
closest.P44 = "S44"
closest.P45 = "S45"
closest.P46 = "S46"
closest.P47 = "S47"
closest.P48 = "S48"
closest.P49 = "S49"
closest.P50 = "S50"
closest.P51 = "S51"
closest.P52 = "S52"
closest.P53 = "S53"
closest.P54 = "S54"
closest.P55 = "S55"
closest.P56 = "S56"
closest.P57 = "S57"
closest.P58 = "S58"
closest.P59 = "S59"
closest.P60 = "S60"
closest.P61 = "S61"
closest.P62 = "S62"
closest.P63 = "S63"
closest.P64 = "S64"
closest.P65 = "S65"
closest.P66 = "S66"
closest.P67 = "S67"
closest.P68 = "S68"
closest.P69 = "S69"
closest.P70 = "S70"
closest.P71 = "S71"
closest.P72 = "S72"
closest.P73 = "S73"
closest.P74 = "S74"
closest.P75 = "S75"
closest.P76 = "S76"
closest.P77 = "S77"
closest.P78 = "S78"
closest.P79 = "S79"
closest.P80 = "S80"
closest.P81 = "S81"
closest.P82 = "S82"
closest.P83 = "S83"
closest.P84 = "S84"
closest.P85 = "S85"
closest.P86 = "S86"
closest.P87 = "S87"
closest.P88 = "S88"
closest.P89 = "S89"
closest.P90 = "S90"
closest.P91 = "S91"
closest.P92 = "S92"
closest.P93 = "S93"
closest.P94 = "S94"
closest.P95 = "S95"
closest.P96 = "S96"
closest.P97 = "S97"
closest.P98 = "S98"
closest.P99 = "S99"
closest.P100 = "S100"
closest.P101 = "S101"
closest.P102 = "S102"
closest.P103 = "S103"
closest.P104 = "S104"
closest.P105 = "S105"
closest.P106 = "S106"
closest.P107 = "S107"
closest.P108 = "S108"
closest.P109 = "S109"
closest.P110 = "S110"
closest.P111 = "S111"
closest.P112 = "S112"
closest.P113 = "S113"
closest.P114 = "S114"
closest.P115 = "S115"
closest.P116 = "S116"
closest.P117 = "S117"
closest.P118 = "S118"
closest.P119 = "S119"

