[server]
host = "127.0.0.1"

[api]
url = "http://127.0.0.1:4200/api"

[server.database]
connection_url = "sqlite+aiosqlite:///var/qcos/db/prefect.db"
connection_timeout = 30

[logging]
level = "INFO"
file_path = "/var/log/qcos/prefect.log"
format = "%(asctime)s %(process)d %(levelname)s [%(name)s] %(message)s"

[results]
local_storage_path = "/var/qcos/storage"
