[qiskit_qasm_sim]
alias_name = "IBM-Qiskit-QASM模拟器"
driver = "DriverQiskitQasmSim"
description = "IBM-Qiskit-QASM模拟器(qiskit-qasm-sim)"

# [Optional] max qubits of device
# device_max_qubits = 100

# [Optional] debug
# debug = false
debug = false

# [Optional] device log file path
# device_log_file = /var/log/qcos/device_qiskit_qasm_sim.log
device_log_file = "/var/log/qcos/device_qiskit_qasm_sim.log"

# [Optional] device monitor log file path
# monitor_log_file = /var/log/qcos/device_montior_qiskit_qasm_sim.log
monitor_log_file = "/var/log/qcos/device_monitor_qiskit_qasm_sim.log"

# [Optional] device manager log file path
# mgr_log_file = /var/log/qcos/device_mgr_qiskit_qasm_sim.log

# [Optional] max queued jobs, -1 means unlimited
max_queued_jobs = -1
