[stim]
alias_name = "QEC专用仿真器"
driver = "DriverStim"
description = "QEC专用仿真器(stim)"

# [Optional] max qubits of device
# device_max_qubits = 10

# [Optional] debug
debug = false

# [Optional] device log file path
# device_log_file = /var/log/qcos/device_stim.log

# [Optional] device manager log file path
# mgr_log_file = /var/log/qcos/device_mgr_stim.log

# [Optional] log format string
# log_format = "%(asctime)s | %(levelname)s | %(module)s:%(lineno)s %(message)s"

# [Optional] log rotate, max_size (MB). default: 10MB
# log_rotate_max_size_mb = 10

# [Optional] log rotate, backup count. default: 10
# log_rotate_backup_count = 10

# [Optional] log rotate, compression. default: true
# log_rotate_compression = true

# [Optional] max queued jobs, -1 means unlimited
max_queued_jobs = -1

[stim.device_monitor]
# [Optional] enable device monitor
enable_device_monitor = false

# [Optional] device monitor log file path
# monitor_log_file = /var/log/qcos/device_monitor_stim.log

# [Optional] monitor polling interval (secs)
polling_interval = 60
