[uqc_matrix2]
alias_name = "幺正量子 UQC-Matrix2 离子阱驱动"
driver = "DriverUQCMatrix2"
description = "幺正量子 UQC-Matrix2 离子阱驱动"

# [Optional] max qubits of device
# device_max_qubits = 100

# [Optional] debug
# debug = false
debug = false

# [Optional] device log file path
# device_log_file = /var/log/qcos/device_uqc_matrix2.log
device_log_file = "/var/log/qcos/device_uqc_matrix2.log"

# [Optional] device manager log file path
# mgr_log_file = /var/log/qcos/device_mgr_uqc_matrix2.log

# [Optional] log format string
# log_format = "%(asctime)s | %(levelname)s | %(module)s:%(lineno)s %(message)s"

# [Optional] log rotate, max_size (MB). default: 10MB
# log_rotate_max_size_mb = 10

# [Optional] log rotate, backup count. default: 10
# log_rotate_backup_count = 10

# [Optional] log rotate, compression. default: true
# log_rotate_compression = true

# [Optional] max queued jobs, -1 means unlimited
max_queued_jobs = -1

# [Optional] max job wait time, default value is 604800 seconds (7 days)
max_job_wait_time = 604800

# [Optional] job query interval, default value is 5 seconds
job_query_interval = 5

uqc_host = "127.0.0.1"
uqc_port = 8003
password_token = "123456789"
# backend_device_name: "Matrix2" or "qiskit-sim"
backend_device_name = "Matrix2"

[uqc_matrix2.device_monitor]
# [Optional] enable device monitor
enable_device_monitor = false

# [Optional] device monitor log file path
monitor_log_file = "/var/log/qcos/device_monitor_uqc_matrix2.log"

# [Optional] monitor polling interval (secs)
polling_interval = 60
