# 性能测试基础参数，默认注释的参数可以忽略
[transpile]
# 性能测试运行次数
# run_count = 1
# 输出日志文件路径和性能测试结果文件，绝对路径或项目的相对路径
# output_log = ""
# csv_file = ""

# 测试集必须配置，绝对路径或项目的相对路径
files = ["./samples/qasm/2.0/simple-qasm.qasm"]
dirs = []

# 允许输入的日志标签，当log_tags为空，则默认允许所有标签
# 当前支持PERF, WARNING, ERROR, DEBUG等标签
# log_tags = ["PERF", "WARNING", "ERROR"]
log_tags = ["WARNING", "ERROR"]

[transpile.transpiler]
# 默认为true
# enable_transpiler = true
# base_gates中元素与拓扑类型强相关
base_gates = ["rx, ry, cx"]

[transpile.optimize]
# 默认opt_level为[1]
opt_level = [0, 1]

[transpile.mapping]
# 默认为true
# enable_mapping = true
# 拓扑类型, 当is_exec不为false时, 拓扑信息必须配置
tech_type = ["superconducting"]
# 拓扑类型配置文件, 当is_exec不为false时， 必须配置，绝对路径或项目的相对路径
config_file = ["./etc/qcos/conf.d/spinq_rpc.toml"]

# 拓扑类型选择中性原子（neutral_atom）时，支持配置选择mapping算法
# 支持的算法："default"、"ZAP"、"ZAC"
# na_mapping_type = "default"

# json格式的字符串，表示不同算法组合输入，默认不输入，
# 但元素必须与tech_type和config_file一一对应
# mapping_options = ["""
#     {
#             "routing_algorithm": "sc",
#             "select_mode": ["KS", 2],
#             "use_prune": 1,
#             "use_hash": 1,
#             "score_layer": 1,
#             "mode_sim": ["fix_cx_num", [10, 3]],
#             "score_decay_rate_size": 0.7,
#             "score_decay_rate_depth": 0.85
#     }
# """]
