#!/usr/bin/env python3
# -*- coding: utf-8 -*-
# ----------------------------------------------------------------------
# Copyright© 2024-2026 China Mobile (SuZhou) Software Technology Co.,Ltd.
#
# qcos is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions
# of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#         http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS,
#     WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.
# ----------------------------------------------------------------------

"""Binding qcos transpiler cpp functions."""

from typing import (
    overload,
)
import collections.abc
import high_performance

class BaseOperation:
    """None."""

    def __init__(
        self,
        name: str,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class C3SQRTX:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class C3X:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class C4X:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class CCX:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class CH:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class CP:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class CRX:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class CRY:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class CRZ:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class CS:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class CSDG:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class CSWAP:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class CSX:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class CU:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class CU1:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class CU3:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class CX:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class CY:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class CZ:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class Control:
    """None."""

    def __init__(
        self, qubit: int = 0, type: high_performance.ControlType = True
    ) -> None: ...
    @property
    def qubit(self) -> int: ...
    @qubit.setter
    def qubit(self, arg: int, /) -> None: ...
    @property
    def type(self) -> high_performance.ControlType: ...
    @type.setter
    def type(self, arg: high_performance.ControlType, /) -> None: ...

class ControlType:
    """None."""

    Neg: ControlType

    Pos: ControlType

    name: property

    value: property

class CppMCTSRouting:
    """C++ implementation of MCTS routing."""

    def __init__(self, selec_times: int = 5) -> None: ...
    def execute_routing(
        self,
        search_tree: object,
        ag: object,
        initial_layout: dict,
        num_q_vir: int,
        measure_ops: list,
    ) -> tuple: ...
    @property
    def selec_times(self) -> int: ...
    @selec_times.setter
    def selec_times(self, arg: int, /) -> None: ...

class DCX:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

DOUBLE_QUBIT_OPERATION: OperationType

class Decomposer:
    """None."""

    def __init__(self) -> None: ...
    def apply_decompose_rules(
        self,
        circuit: collections.abc.Sequence[high_performance.BaseOperation],
        table: collections.abc.Mapping[
            high_performance.ParamGate,
            collections.abc.Sequence[high_performance.ParamGate],
        ],
    ) -> list[high_performance.BaseOperation]: ...
    def get_decompose_rules(
        self,
        arg0: collections.abc.Sequence[str],
        arg1: collections.abc.Sequence[str],
        /,
    ) -> tuple: ...

class ECR:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

FIVE_QUBIT_OPERATION: OperationType

FOUR_QUBIT_OPERATION: OperationType

class GateOperation:
    """None."""

    def __init__(
        self,
        name: str,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
        hermitian: bool = False,
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class GreedyRouting:
    """Greedy blocked-gate routing."""

    def __init__(
        self, coupling_list: collections.abc.Sequence[tuple[int, int]]
    ) -> None: ...
    def execute(
        self,
        gates_list: collections.abc.Sequence[high_performance.GateOperation],
        initial_l2p: collections.abc.Sequence[int] = [],
    ) -> None: ...
    def get_physical_gates(self) -> list[high_performance.GateOperation]: ...
    @property
    def logic2phy(self) -> list[int]: ...
    @property
    def phy2logic(self) -> list[int]: ...

class H:
    """None."""

    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class ISWAP:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

MEASURE: OperationType

MOVE: OperationType

class Measure:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class Move:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

Neg: ControlType

class OpType:
    """None."""

    name: property

    otAFalse: OpType

    otATrue: OpType

    otBarrier: OpType

    otC3SQRTX: OpType

    otC3X: OpType

    otC4X: OpType

    otCCZ: OpType

    otCH: OpType

    otCNOT: OpType

    otCP: OpType

    otCRX: OpType

    otCRY: OpType

    otCRZ: OpType

    otCS: OpType

    otCSWAP: OpType

    otCSX: OpType

    otCSdg: OpType

    otCU: OpType

    otCU3: OpType

    otCY: OpType

    otCZ: OpType

    otClassicControlled: OpType

    otCompound: OpType

    otDCX: OpType

    otECR: OpType

    otGPhase: OpType

    otH: OpType

    otI: OpType

    otMeasure: OpType

    otMultiAFalse: OpType

    otMultiATrue: OpType

    otNone: OpType

    otOpCount: OpType

    otP: OpType

    otPeres: OpType

    otPeresdg: OpType

    otR: OpType

    otRC3X: OpType

    otRCCX: OpType

    otRX: OpType

    otRXX: OpType

    otRY: OpType

    otRYY: OpType

    otRZ: OpType

    otRZX: OpType

    otRZZ: OpType

    otReset: OpType

    otS: OpType

    otSWAP: OpType

    otSX: OpType

    otSXdg: OpType

    otSdg: OpType

    otT: OpType

    otTOFFOLI: OpType

    otTdg: OpType

    otTeleportation: OpType

    otU: OpType

    otU1: OpType

    otU2: OpType

    otU3: OpType

    otV: OpType

    otVdg: OpType

    otW: OpType

    otX: OpType

    otXXminusYY: OpType

    otXXplusYY: OpType

    otY: OpType

    otZ: OpType

    ot_iSWAP: OpType

    ot_iSWAPdg: OpType

    value: property

class Operation:
    """None."""

    def __init__(*args, **kwargs):
        """Initialize self.  See help(type(self)) for accurate signature."""
        ...

    @property
    def controls(self) -> set[high_performance.Control]: ...
    @property
    def name(self) -> str: ...
    @property
    def parameter(self) -> list[float]: ...
    @property
    def targets(self) -> list[int]: ...
    @property
    def type(self) -> high_performance.OpType: ...

class OperationType:
    """None."""

    DOUBLE_QUBIT_OPERATION: OperationType

    FIVE_QUBIT_OPERATION: OperationType

    FOUR_QUBIT_OPERATION: OperationType

    MEASURE: OperationType

    MOVE: OperationType

    SINGLE_QUBIT_OPERATION: OperationType

    SYNC: OperationType

    TRIPLE_QUBIT_OPERATION: OperationType

    name: property

    value: property

class P:
    """None."""

    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class ParamGate:
    """None."""

    def __init__(self) -> None: ...
    @property
    def name(self) -> str: ...
    @name.setter
    def name(self, arg: str, /) -> None: ...
    @property
    def params(self) -> list[str]: ...
    @params.setter
    def params(self, arg: collections.abc.Sequence[str], /) -> None: ...
    @property
    def qubits(self) -> list[str]: ...
    @qubits.setter
    def qubits(self, arg: collections.abc.Sequence[str], /) -> None: ...

Pos: ControlType

class QasmConverter:
    """Convert a QuantumCircuit to QASM2/QASM3 string or file."""

    def __init__(self, circuit: high_performance.QuantumCircuit) -> None: ...
    def to_qasm2(self) -> str: ...
    def to_qasm3(self) -> str: ...
    def save(self, path: str, version: str = "2.0") -> None: ...

class QuantumCircuit:
    """Quantum circuit."""

    def __init__(
        self,
        num_qubits: int = 0,
        num_clbits: int = 0,
        global_phase: float = 0.0,
    ) -> None: ...
    @staticmethod
    def from_ir(
        ir: collections.abc.Sequence[high_performance.BaseOperation],
        num_qubits: int = 0,
    ) -> high_performance.QuantumCircuit: ...
    def append(self, operation: high_performance.BaseOperation) -> None: ...
    def append_operations(
        self,
        operations: collections.abc.Sequence[high_performance.BaseOperation],
    ) -> None: ...
    def get_operations(self) -> list[high_performance.BaseOperation]: ...
    def num_qubits(self) -> int: ...
    def num_clbits(self) -> int: ...
    def global_phase(self) -> float: ...
    def set_global_phase(self, phase: float) -> None: ...
    def set_num_qubits(self, num_qubits: int) -> None: ...
    def set_num_clbits(self, num_clbits: int) -> None: ...
    def depth(self) -> int: ...
    def width(self) -> int: ...
    def size(self) -> int: ...

class R:
    """None."""

    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class RC3X:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class RCCX:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class RX:
    """None."""

    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class RXX:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class RY:
    """None."""

    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class RYY:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class RZ:
    """None."""

    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class RZX:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class RZZ:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class Reset:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class S:
    """None."""

    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class SABRE:
    """SABRE quantum routing algorithm."""

    def __init__(
        self,
        coupling_list: collections.abc.Sequence[tuple[int, int]],
        edge_fidelities: collections.abc.Sequence[float] = [],
        single_qubit_fidelities: collections.abc.Sequence[float] = [],
        fidelity_threshold: float = -1.0,
        extension_size: int = 20,
        weight: float = 0.5,
        decay: float = 0.001,
        fidelity_weight: float = 0.5,
    ) -> None:
        """Construct a SABRE router.

        Args:
        coupling_list (list[tuple[int, int]]): Physical qubit connectivity
            graph.
        edge_fidelities (list[float], optional): Edge fidelity values
            corresponding to coupling_list. Empty means not used.
        single_qubit_fidelities (list[float], optional): Single-qubit
            fidelity array indexed by physical qubit ID. Empty means not used.
        fidelity_threshold (float, optional): Fidelity threshold for filtering
            low-fidelity edges. Negative value means adaptive calculation
            (mean - std, clamped to [0.3, 0.9]). Defaults to -1.0 (adaptive).
        extension_size (int, optional): Size of the lookahead set.
            Defaults to 20.
        weight (float, optional): Weight between front layer and lookahead
            cost. Defaults to 0.5.
        decay (float, optional): SWAP decay coefficient. Defaults to 0.001.
        fidelity_weight (float, optional): DenseLayout fidelity weight in
            [0, 1]. 0.0 = pure density, 1.0 = pure fidelity. Defaults to 0.5.
        """
        ...

    def execute(
        self,
        gates_list: collections.abc.Sequence[high_performance.BaseOperation],
    ) -> None:
        """Execute SABRE routing.

        Args:
        gates_list (list[BaseOperation]): Logical gate sequence.

        Returns:
        None
        """
        ...

    def get_final_mapping(self) -> list[int]:
        """Get the final logical-to-physical mapping after routing.

        Returns:
        list[int]: The index is logical qubit and value is physical qubit.
        """
        ...

    def get_initial_mapping(self) -> list[int]:
        """Get the initial logical-to-physical mapping.

        Must be called after execute().

        Returns:
        list[int]: The index is logical qubit and value is physical qubit.
        """
        ...

    def get_physical_gates(self) -> list[high_performance.BaseOperation]:
        """Get the sequence of mapped physical gates after routing.

        Returns:
        list[BaseOperation]: The physical gate sequence.
        """
        ...

class SDG:
    """None."""

    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

SINGLE_QUBIT_OPERATION: OperationType

class SWAP:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class SX:
    """None."""

    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class SXDG:
    """None."""

    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

SYNC: OperationType

class Sync:
    """None."""

    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float],
        operation_type: high_performance.OperationType,
    ) -> None: ...
    @overload
    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class T:
    """None."""

    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class TDG:
    """None."""

    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

TRIPLE_QUBIT_OPERATION: OperationType

class U:
    """None."""

    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class U1:
    """None."""

    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class U2:
    """None."""

    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class U3:
    """None."""

    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class X:
    """None."""

    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class Y:
    """None."""

    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

class Z:
    """None."""

    def __init__(
        self,
        targets: collections.abc.Sequence[int],
        arg_value: collections.abc.Sequence[float] = [],
    ) -> None: ...
    @property
    def arg_value(self) -> list[float]: ...
    @arg_value.setter
    def arg_value(self, arg: collections.abc.Sequence[float], /) -> None: ...
    def arg_value_to_string(self) -> str: ...
    def decompose_to_1q2q(self) -> list[high_performance.BaseOperation]: ...
    def default_decompose(self) -> list[high_performance.BaseOperation]: ...
    @property
    def hermitian(self) -> bool: ...
    @property
    def name(self) -> str: ...
    @property
    def operation_type(self) -> high_performance.OperationType: ...
    @property
    def targets(self) -> list[int]: ...
    @targets.setter
    def targets(self, arg: collections.abc.Sequence[int], /) -> None: ...
    def targets_to_string(self) -> str: ...
    def to_matrix(self) -> list[complex]: ...
    def to_openqasm(self, qubit_prefix: str = "q") -> str: ...

def qasm_to_ir(
    qasm_str: str,
) -> tuple[list[high_performance.BaseOperation], int]:
    """将QASM字符串转换为操作列表.

    Args:
    qasm_str: QASM格式的量子电路字符串

    Returns:
    返回解析得到的量子操作列表

    Example:
    >>> import high_performance
    >>> qasm = "OPENQASM 2.0; qreg q[2]; h q[0]; cx q[0], q[1];"
    >>> ops, num_qubits = high_performance.qasm_to_ir(qasm)
    >>> print(f"解析到 {len(ops)} 个操作")
    """
    ...

def create_gate(
    name: str,
    targets: collections.abc.Sequence[int] = [],
    arg_value: collections.abc.Sequence[float] = [],
    allow_undefined: bool = False,
) -> high_performance.BaseOperation:
    """Create a gate or operation instance by name."""
    ...

def load_config_file(filename: str) -> list[tuple[int, int]]:
    """从配置文件中加载量子芯片耦合列表.

    Args:
    filename (str): 配置文件路径

    Returns:
    list[tuple[int,int]]: 耦合对列表
    """
    ...

def load_qasm_to_gate_list(
    filename: str,
) -> list[high_performance.GateOperation]:
    """将QASM文件加载为门操作列表.

    Args:
    filename (str): QASM文件路径

    Returns:
    list[GateOperation]: 解析得到的门操作列表
    """
    ...

def optimize(
    ir: collections.abc.Sequence[high_performance.BaseOperation],
    opt_level: int = 1,
    verbose: bool = False,
    basis_gates: collections.abc.Set[str] | None = None,
    num_threads: int = 1,
) -> list[high_performance.BaseOperation]:
    """对 IR 执行优化.

    opt_level:
    0 - 不做优化
    1 - InverseCancellation + AdjacentPhaseOptPass
    2 - Level 1 + EquivalencePass
    3 - Level 2 + CliffordRzOptimization

    num_threads:
    1 - 串行（默认）
    0 - 自动并行（线程数取硬件并发数）
    >1 - 指定线程数并行

    Args:
    ir (list[BaseOperation]): 待优化的操作序列
    opt_level (int, optional): 优化级别. Defaults to 1.
    verbose (bool, optional): 是否打印优化详情. Defaults to False.
    basis_gates (set[str] | None, optional): basis gate 过滤集合.
    num_threads (int, optional): 并行线程数：1=串行，0=自动，>1=指定.
                                 Defaults to 1.

    Returns:
    list[BaseOperation]: 优化后的操作序列
    """
    ...

otAFalse: OpType

otATrue: OpType

otBarrier: OpType

otC3SQRTX: OpType

otC3X: OpType

otC4X: OpType

otCCZ: OpType

otCH: OpType

otCNOT: OpType

otCP: OpType

otCRX: OpType

otCRY: OpType

otCRZ: OpType

otCS: OpType

otCSWAP: OpType

otCSX: OpType

otCSdg: OpType

otCU: OpType

otCU3: OpType

otCY: OpType

otCZ: OpType

otClassicControlled: OpType

otCompound: OpType

otDCX: OpType

otECR: OpType

otGPhase: OpType

otH: OpType

otI: OpType

otMeasure: OpType

otMultiAFalse: OpType

otMultiATrue: OpType

otNone: OpType

otOpCount: OpType

otP: OpType

otPeres: OpType

otPeresdg: OpType

otR: OpType

otRC3X: OpType

otRCCX: OpType

otRX: OpType

otRXX: OpType

otRY: OpType

otRYY: OpType

otRZ: OpType

otRZX: OpType

otRZZ: OpType

otReset: OpType

otS: OpType

otSWAP: OpType

otSX: OpType

otSXdg: OpType

otSdg: OpType

otT: OpType

otTOFFOLI: OpType

otTdg: OpType

otTeleportation: OpType

otU: OpType

otU1: OpType

otU2: OpType

otU3: OpType

otV: OpType

otVdg: OpType

otW: OpType

otX: OpType

otXXminusYY: OpType

otXXplusYY: OpType

otY: OpType

otZ: OpType

ot_iSWAP: OpType

ot_iSWAPdg: OpType

def sabre_initial_mapping(
    gates_list: collections.abc.Sequence[high_performance.GateOperation],
    coupling_list: collections.abc.Sequence[tuple[int, int]],
) -> list[int]:
    """Get the initial mapping using the SABRE algorithm.

    Args:
    gates_list (list[GateOperation]): Logical gate sequence.
    coupling_list (list[tuple[int, int]]): Physical qubit coupling list.

    Returns:
    list[int]: The initial logical-to-physical mapping.
    """
    ...

def sabre_routing(
    gates_list: collections.abc.Sequence[high_performance.BaseOperation],
    coupling_list: collections.abc.Sequence[tuple[int, int]],
    edge_fidelities: collections.abc.Sequence[float] = [],
    single_qubit_fidelities: collections.abc.Sequence[float] = [],
    fidelity_threshold: float = -1.0,
    extension_size: int = 20,
    weight: float = 0.5,
    decay: float = 0.001,
    fidelity_weight: float = 0.5,
) -> list[high_performance.BaseOperation]:
    """Execute SABRE routing.

    Args:
    gates_list (list[BaseOperation]): Logical operation sequence.
    coupling_list (list[tuple[int, int]]): Physical qubit coupling list.
    edge_fidelities (list[float], optional): Edge fidelity values
        corresponding to coupling_list. Empty means not used.
    single_qubit_fidelities (list[float], optional): Single-qubit fidelity
        array indexed by physical qubit ID. Empty means not used.
    fidelity_threshold (float, optional): Fidelity threshold for filtering
        low-fidelity edges. Negative value means adaptive calculation
        (mean - std, clamped to [0.3, 0.9]). Defaults to -1.0 (adaptive).
    extension_size (int, optional): Size of the lookahead set.
    Defaults to 20.
    weight (float, optional): Weight between front layer and lookahead cost.
    Defaults to 0.5.
    decay (float, optional): SWAP decay coefficient. Defaults to 0.001.
    fidelity_weight (float, optional): DenseLayout fidelity weight in [0, 1].
        0.0 = pure density, 1.0 = pure fidelity. Defaults to 0.5.

    Returns:
    list[BaseOperation]: The routed physical operation sequence.
    """
    ...

class TranspileTimings:
    """Timing breakdown for each transpile stage."""

    decompose_1q2q_time: float
    decompose_apply_time: float
    decompose_rule_time: float
    mapping_time: float
    opt_time1: float
    opt_time2: float
    parse_time: float
    total_time: float
    transpile_time: float

    def __init__(self) -> None: ...

class TranspileResult:
    """Result of the all-in-one transpile function."""

    basis_gate_list: list[high_performance.BaseOperation]
    num_qubits: int
    timings: high_performance.TranspileTimings

    def __init__(self) -> None: ...

def transpile(
    qasm_string: str,
    supp_basis_gates: collections.abc.Sequence[str],
    opt_level: int = 1,
    coupling_list: collections.abc.Sequence[tuple[int, int]] = [],
    edge_fidelities: collections.abc.Sequence[float] = [],
    single_qubit_fidelities: collections.abc.Sequence[float] = [],
    layout_method: str = "vf2_layout",
    num_threads: int = 0,
    fast_mode: bool = True,
    fidelity_threshold: float = -1.0,
    fidelity_weight: float = 0.5,
) -> high_performance.TranspileResult:
    """All-in-one transpile function (sabre routing, single-circuit path).

    Combines parse + transpile into a single C++ call, avoiding intermediate
    Python/C++ data transfer overhead.

    Args:
    qasm_string (str): QASM circuit string.
    supp_basis_gates (list[str]): Supported basis gate names.
    opt_level (int, optional): Optimization level (0-3). Defaults to 1.
    coupling_list (list[tuple[int, int]], optional): Physical qubit coupling
        edges. Empty means skip routing.
    edge_fidelities (list[float], optional): Edge fidelity values
        corresponding to coupling_list. Empty means not used.
    single_qubit_fidelities (list[float], optional): Single-qubit fidelity
        array indexed by physical qubit ID. Empty means not used.
    layout_method (str, optional): Initial layout method: "vf2_layout"
        (default) or "dense_layout".
    num_threads (int, optional): Optimization thread count. 0 = auto
        (hardware_concurrency), 1 = serial, >1 = explicit. Defaults to 0.
    fast_mode (bool, optional): Optimization fast mode. True = run pass
        list only once. Defaults to True.
    fidelity_threshold (float, optional): Fidelity threshold; edges
        below this value are filtered out. Negative value means adaptive
        calculation (mean - std, clamped to [0.3, 0.9]).
        Defaults to -1.0 (adaptive).
    fidelity_weight (float, optional): DenseLayout fidelity weight in [0, 1].
        0.0 = pure density, 1.0 = pure fidelity. Defaults to 0.5.

    Returns:
    TranspileResult: Contains basis_gate_list, num_qubits, and timings.
    """
    ...

def transpile_na(
    qasm_string: str,
    supp_basis_gates: collections.abc.Sequence[str],
    qpu_cfg: dict,
    opt_level: int = 1,
) -> high_performance.TranspileResult:
    """All-in-one transpile function (neutral-atom NA mappin).

    Same pipeline as ``transpile`` (sabre) but the routing stage uses NARoute,
    inserting MOVE operations between the storage and operate areas so that
    two-qubit gates act on adjacent sites.

    Args:
    qasm_string (str): QASM circuit string.
    supp_basis_gates (list[str]): Supported basis gate names.
    qpu_cfg (dict): Neutral-atom QPU configuration with keys
        ``storage_area``, ``operate_area``, ``coupler_map`` and
        ``readout_error``.
    opt_level (int, optional): Optimization level (0-3). Defaults to 1.

    Returns:
    TranspileResult: Contains basis_gate_list, num_qubits, and timings.
    """

class ChipCalibration:
    """Chip calibration data."""

    coupling_list: list[tuple[int, int]]
    edge_fidelities: list[float]
    single_qubit_fidelities: list[float]

    def __init__(
        self,
        coupling_list: collections.abc.Sequence[tuple[int, int]],
        edge_fidelities: collections.abc.Sequence[float],
        single_qubit_fidelities: collections.abc.Sequence[float],
    ) -> None: ...

def load_chip_calibration(csv_path: str) -> high_performance.ChipCalibration:
    """Load chip calibration data from a CSV file (北量院).

    Args:
    csv_path (str): Path to the calibration CSV file.

    Returns:
    ChipCalibration: Parsed calibration data.
    """
    ...

class VerifyParams:
    """Verification parameters."""

    bits: int
    basis_gates: list[str]
    coupling_list: list[tuple[int, int]]
    edge_fidelities: list[float]
    single_qubit_fidelities: list[float]
    target_bits: list[int]

    def __init__(self) -> None: ...

class VerifyResult:
    """Verification result with pass/fail status and failure message."""

    passed: bool
    message: str

    def __init__(self) -> None: ...

class QuafuVerifier:
    """Quafu (夸父) superconducting chip verifier."""

    def __init__(self, params: high_performance.VerifyParams) -> None: ...
    def verify(
        self, qasm_string: str, verbose: bool = False
    ) -> high_performance.VerifyResult: ...
