# Driver running environments

[default]
deps_filepath = "./requirements-qcos.txt"
envs = ["python3-qcos"]

[pypy]
deps_filepath = "./requirements-transpiler-cmss.txt"
envs = ["pypy3"]

[DriverQutipSim]
module_name = "driver_qutip_sim"
deps_filepath = "./drivers/requirements-qutip.txt"
envs = ["python3-qcos"]

[DriverSpinQRpc]
module_name = "driver_spinq_rpc"
deps_filepath = "./drivers/requirements-spinq-rpc.txt"
envs = ["python3-qcos"]

[DriverUQCMatrix2]
module_name = "driver_uqc"
deps_filepath = "./drivers/requirements-uqc.txt"
envs = ["python3-qcos"]

[qiskit]
deps_filepath = "./drivers/requirements-qiskit.txt"
envs = ["python3-qcos"]

[DriverQiskitQasmSim]
module_name = "driver_qiskit_qasm_sim"
copy_from = "qiskit"

[DriverQiskitAerSim]
module_name = "driver_qiskit_aer_sim"
copy_from = "qiskit"
