# ----------------------------------------------------------------------
# Copyright© 2025-2025 China Mobile (SuZhou) Software Technology Co.,Ltd.
#
# qcos is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions
# of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#         http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.
# ----------------------------------------------------------------------

# Create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: ${QCOS_NAMESPACE}
---
# Deploy prefect-server
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prefect-server
  namespace: ${QCOS_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prefect-server
  template:
    metadata:
      labels:
        app: prefect-server
    spec:
      hostNetwork: false
      restartPolicy: Always
      initContainers:
      - name: init-prefect-server
        image: ${REGISTRY}${QCOS_IMAGE_NAME}:${QCOS_IMAGE_VERSION}
        imagePullPolicy: IfNotPresent
        command: [
          'sh', '-c',
          'mkdir -p /var/qcos/db/; mkdir -p /var/qcos/storage'
        ]
        volumeMounts:
        - name: code-data
          mountPath: /root/qcos-project
        #- name: database-dir
        #  mountPath: /var/qcos
      containers:
      - name: prefect-server
        image: ${REGISTRY}${PREFECT_IMAGE_NAME}:${PREFECT_IMAGE_VERSION}
        imagePullPolicy: IfNotPresent
        command: ["prefect", "server", "start", "--host", ""]
        env:
        - name: TZ
          value: "Asia/Shanghai"
        - name: PREFECT_SERVER_API_HOST
          value: "${PREFECT_SERVER_API_HOST}"
        - name: PREFECT_API_URL
          value: "${PREFECT_API_URL}"
        - name: PREFECT_SERVER_DATABASE_CONNECTION_URL
          value: "sqlite+aiosqlite:////tmp/prefect.db"
          #value: "sqlite+aiosqlite:////var/qcos/db/prefect.db"
        - name: PREFECT_API_DATABASE_TIMEOUT
          value: "30"
        - name: PREFECT_LOCAL_STORAGE_PATH
          value: "/var/qcos/storage"
        - name: PREFECT_API_DEFAULT_LIMIT
          value: "100000"
        resources:
          requests:
            cpu: "2000m"
            memory: "4Gi"
          limits:
            cpu: "4000m"
            memory: "8Gi"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 4200
          initialDelaySeconds: 60
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /api/health
            port: 4200
          initialDelaySeconds: 10
          periodSeconds: 60
          timeoutSeconds: 10
          successThreshold: 1
        volumeMounts:
        - name: code-data
          mountPath: /root/qcos-project
        #- name: database-dir
        #  mountPath: /var/qcos
      volumes:
      - name: code-data
        persistentVolumeClaim:
          claimName: ${K8S_CODE_DATA_PVC}
      #- name: database-dir
      #  persistentVolumeClaim:
      #    claimName: ${K8S_DATABASE_PVC}
#      nodeSelector:
#        qcos-prefect: enabled
#      affinity:
#        podAntiAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#          - labelSelector:
#              matchLabels:
#                app: prefect-server
#            topologyKey: "kubernetes.io/hostname"
---
# prefect-server service (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: prefect-server
  namespace: ${QCOS_NAMESPACE}
spec:
  selector:
    app: prefect-server
  type: ClusterIP
  ports:
  - port: ${PREFECT_SERVER_PORT}
    targetPort: 4200
---
# Deploy qcos
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${QCOS_CONTAINER_NAME}
  namespace: ${QCOS_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${QCOS_CONTAINER_NAME}
  template:
    metadata:
      labels:
        app: ${QCOS_CONTAINER_NAME}
    spec:
      hostNetwork: false
      restartPolicy: Always
      initContainers:
      - name: wait-prefect-server
        # copy qcos engine code and wait prefect server
        image: ${REGISTRY}${QCOS_IMAGE_NAME}:${QCOS_IMAGE_VERSION}
        imagePullPolicy: Always
        command: [
          'sh', '-c',
          'rm -rf /mnt/shared/qcos; cp -rf /root/qcos-project/qcos /mnt/shared/; echo "prefect-server: http://prefect-server.${QCOS_NAMESPACE}:${PREFECT_SERVER_PORT}/api"; until wget -q --spider http://prefect-server.${QCOS_NAMESPACE}:${PREFECT_SERVER_PORT}/api; do echo "waiting for prefect-server ..."; sleep 2; done; echo "prefect-server is ready"'
        ]
        volumeMounts:
          - name: code-data
            mountPath: /mnt/shared
      containers:
      - name: ${QCOS_CONTAINER_NAME}
        image: ${REGISTRY}${QCOS_IMAGE_NAME}:${QCOS_IMAGE_VERSION}
        imagePullPolicy: Always
        # securityContext:
        #   privileged: true
        stdin: true
        tty: true
        workingDir: /root
        # command: ["/bin/sleep", "infinity"]
        command: ["/entrypoint.sh"]
        env:
        - name: DEBUG
          value: "${DEBUG}"
        - name: DEV
          value: "${DEV}"
        - name: TZ
          value: "Asia/Shanghai"
        - name: QCOS_CONTAINER_NAME
          value: "${QCOS_CONTAINER_NAME}"
        - name: API_SERVER_LISTEN_IP
          value: "${QCOS_API_SERVER_IP}"
        - name: API_SERVER_LISTEN_PORT
          value: "${QCOS_API_SERVER_PORT}"
        - name: QCOS_ENABLE_VIRT
          value: "${QCOS_ENABLE_VIRT}"
        #- name: PREFECT_SERVER_API_HOST
        #  value: "${PREFECT_SERVER_API_HOST}"
        - name: PREFECT_API_URL
          value: "${PREFECT_API_URL}"
        - name: PREFECT_SERVER_DATABASE_CONNECTION_URL
          value: "sqlite+aiosqlite:///var/qcos/db/prefect.db"
        - name: PREFECT_LOCAL_STORAGE_PATH
          value: "/var/qcos/storage"
        - name: PYTHONPATH
          value: "/root/qcos-project"
        - name: QCOS_SERVER_IP
          value: "${QCOS_SERVER_IP}"
        - name: QCOS_SERVER_PORT
          value: "${QCOS_SERVER_PORT}"
        - name: QCOS_VIRTUAL_INSTANCE_ID
          value: "${QCOS_ADMIN_VIRTUAL_INSTANCE_ID}"
        resources:
          requests:
            cpu: "1000m"
            memory: "2Gi"
          limits:
            cpu: "2000m"
            memory: "4Gi"
        livenessProbe:
          tcpSocket:
            port: ${QCOS_API_SERVER_PORT}
          initialDelaySeconds: 30
          periodSeconds: 60
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          tcpSocket:
            port: ${QCOS_API_SERVER_PORT}
          initialDelaySeconds: 5
          periodSeconds: 60
          timeoutSeconds: 10
          successThreshold: 1
        volumeMounts:
        - name: code-data
          mountPath: /root/qcos-project
        #- name: database-dir
        #  mountPath: /var/qcos
        - name: qcos-config
          mountPath: /etc/qcos/qcos.toml
          subPath: qcos.toml
        - name: qcos-config-device-dummy
          mountPath: /etc/qcos/conf.d/dummy.toml
          subPath: dummy.toml
      volumes:
      - name: code-data
        persistentVolumeClaim:
          claimName: ${K8S_CODE_DATA_PVC}
      #- name: database-dir
      #  persistentVolumeClaim:
      #    claimName: ${K8S_DATABASE_PVC}
      - name: qcos-config
        configMap:
          name: qcos-config
      - name: qcos-config-device-dummy
        configMap:
          name: qcos-config
#      affinity:
#        podAffinity:
#          requiredDuringSchedulingIgnoredDuringExecution:
#          - labelSelector:
#              matchExpressions:
#              - key: app
#                operator: In
#                values:
#                - prefect-server
#            topologyKey: "kubernetes.io/hostname"
#      nodeSelector:
#        qcos-api: enabled
---
# qcos service (ClusterIP)
apiVersion: v1
kind: Service
metadata:
  name: ${QCOS_CONTAINER_NAME}
  namespace: ${QCOS_NAMESPACE}
spec:
  selector:
    app: ${QCOS_CONTAINER_NAME}
  type: ClusterIP
  ports:
  - port: ${QCOS_API_SERVER_PORT}
    targetPort: 18400
