# ----------------------------------------------------------------------
# Copyright© 2024-2025 China Mobile (SuZhou) Software Technology Co.,Ltd.
#
# qcos is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions
# of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#         http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.
# ----------------------------------------------------------------------

# Create namespace
apiVersion: v1
kind: Namespace
metadata:
  name: ${QCOS_NAMESPACE}
---
# Create QCOS ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: qcos-config
  namespace: ${QCOS_NAMESPACE}
data:
  qcos.toml: |
    [DEFAULT]
    DEBUG = false
    # [GLOBAL CONFIG] max jobs (all status)
    MAX_JOBS = 10000
    # [GLOBAL CONFIG] max queued+running jobs
    MAX_QUEUED_JOBS = 1000

    [VIRT]
    # enable virtualization
    ENABLE_VIRT = ${QCOS_ENABLE_VIRT}
    # [GLOBAL CONFIG] max jobs for virtual instance
    MAX_JOBS_PER_VIRTUAL_INSTANCE = 10
    # salt for password/encryption
    PASSWORD_SALT = "${QCOS_PASSWORD_SALT}"

    [API_SERVER]
    # API workers
    API_WORKERS = 8
    # API server listen ip
    API_SERVER_LISTEN_IP = ""
    # API server listen port
    API_SERVER_LISTEN_PORT = ${QCOS_API_SERVER_PORT}

    [PREFECT]
    PREFECT_SERVER_DATABASE_CONNECTION_URL = "sqlite+aiosqlite:///var/qcos/db/prefect.db"
    PREFECT_API_URL = ${PREFECT_API_URL}
    PREFECT_WORKER_QUERY_SECONDS = 1
    PREFECT_WORKER_PREFETCH_SECONDS = 1
    PREFECT_WORKER_HEARTBEAT_SECONDS = 30
    PREFECT_LOCAL_STORAGE_PATH = "/var/qcos/storage"
    PREFECT_LOGGING_LEVEL = "INFO"
    
    [REDIS]
    # redis server ip
    REDIS_SERVER_IP = ${REDIS_SERVER_IP}
    # redis server port
    REDIS_SERVER_PORT = ${REDIS_SERVER_PORT}

    [LOG]
    # api log file
    API_LOG_FILE = "/var/log/qcos/qcos-api.log"
    # log format
    LOG_FORMAT = "%(asctime)s | %(levelname)s | %(module)s:%(lineno)s %(message)s"
    # log rotate, max_size (MB). default: 10MB
    LOG_ROTATE_MAX_SIZE_MB = 10
    # log rotate, backup count. default: 10
    LOG_ROTATE_BACKUP_COUNT = 10
    # log rotate, compression. default: true
    LOG_ROTATE_COMPRESSION = true

    [SSL]
    # Enable HTTPS for API server
    USE_SSL = false

    # SSL CERT_FILE
    # eg. CERT_FILE = "/etc/qcos/ssl/ssl.crt"
    # CERT_FILE =

    # SSL KEY_FILE
    # eg. KEY_FILE = "/etc/qcos/ssl/ssl.key"
    # KEY_FILE =

    # SSL CACERT_FILE (Optional)
    # eg. CACERT_FILE = "/etc/qcos/ssl/cacert.pem"
    # CACERT_FILE =

    [DEVICES]
    # DEVICE_LIST example:
    # DEVICE_LIST = ["dummy", "hanyuan1", "wy-hanyuan1", "tiangong100", "tiangong100_v2", "tiangong550_v2", "tiangong1000_v2", "spinq_rpc", "spinq_gemini", "spinq_triangulum", "uqc_matrix2", "qiskit_aer_sim", "qiskit_qasm_sim", "qutip_sim"]
    DEVICE_LIST = ["dummy"]

  dummy.toml: |
    [dummy]
    alias_name = "空载测试设备 1"
    driver = "DriverDummy"
    description = "空载测试设备(dummy) 1"

    [dummy.transpiler.qpu_configs]
    # Samples
    qubits = 6
    storage_area = ["S27", "S28", "S29", "S35", "S36", "S37"]
    operate_area = ["P27", "P28", "P29", "P35", "P36", "P37"]

    coupler_map.G0 = ["P27", "P35"]
    coupler_map.G1 = ["P28", "P36"]
    coupler_map.G2 = ["P29", "P37"]
    coupler_map.G3 = ["P27", "P28"]
    coupler_map.G4 = ["P35", "P36"]
    coupler_map.G5 = ["P28", "P29"]

    readout_error.S27 = 1.0
    readout_error.S28 = 2.0
    readout_error.S35 = 3.0
    readout_error.S36 = 4.0
    readout_error.S29 = 5.0
    readout_error.S37 = 6.0

    coupler_error.G0 = 3.0
    coupler_error.G1 = 3.0
    coupler_error.G2 = 3.0
    coupler_error.G3 = 3.0
    coupler_error.G4 = 3.0
    coupler_error.G5 = 3.0

    closest.P27 = "S27"
    closest.P28 = "S28"
    closest.P35 = "S35"
    closest.P36 = "S36"
    closest.P29 = "S29"
    closest.P37 = "S37"

    [dummy.transpiler.decomposition_rule]
    # Samples
    u3.params = ["a", "b", "c"]
    u3.gates = [
        ["rz", [0], ["c"]],
        ["rx", [0], ["pi/2"]],
        ["rz", [0], ["b+pi"]],
        ["rx", [0], ["pi/2"]],
        ["rz", [0], ["a+pi"]]
    ]
    h.gates = [
        ["rx", [0], ["pi/2"]]
    ]
