[ciqtek_ion_1]
alias_name = "国仪量子 离子阱驱动"
driver = "DriverCiqtekIon1"
description = "国仪量子 离子阱驱动"

# [Optional] max qubits of device
# device_max_qubits = 100

# [Optional] debug
# debug = false
debug = false

# [Optional] device log file path
# device_log_file = /var/log/qcos/device_ciqtek_ion1.log
device_log_file = "/var/log/qcos/device_ciqtek_ion1.log"

# [Optional] device monitor log file path
# monitor_log_file = /var/log/qcos/device_monitor_ciqtek_ion1.log
monitor_log_file = "/var/log/qcos/device_monitor_ciqtek_ion1.log"

# [Optional] device manager log file path
# mgr_log_file = /var/log/qcos/device_mgr_ciqtek_ion1.log
# [Optional] log format string
# log_format = "%(asctime)s | %(levelname)s | %(module)s:%(lineno)s %(message)s"

# [Optional] log rotate, max_size (MB). default: 10MB
# log_rotate_max_size_mb = 10

# [Optional] log rotate, backup count. default: 10
# log_rotate_backup_count = 10

# [Optional] log rotate, compression. default: true
# log_rotate_compression = true

# [Optional] max queued jobs, -1 means unlimited
max_queued_jobs = -1

host = "127.0.0.1"
port = 18605
device_id = "123456789"
