[dummy]
alias_name = "空载测试设备"
driver = "DriverDummy"
description = "空载测试设备(dummy)"

# [Optional] max qubits of device
# device_max_qubits = 10

# [Optional] debug
# debug = false
debug = false

# [Optional] device log file path
# device_log_file = /var/log/qcos/device_dummy.log
device_log_file = "/var/log/qcos/device_dummy.log"

# [Optional] device monitor log file path
# monitor_log_file = /var/log/qcos/device_montior_dummy.log
monitor_log_file = "/var/log/qcos/device_monitor_dummy.log"

# [Optional] device manager log file path
# mgr_log_file = /var/log/qcos/device_mgr_dummy.log

# [Optional] max queued jobs, -1 means unlimited
max_queued_jobs = -1

[dummy.transpiler.qpu_configs]
# Samples
qubits = 36
storage_area = ["P144", "P145", "P146", "P147", "P148", "P149", "P150", "P151", "P152", "P153", "P154", "P155",
                "P164", "P165", "P166", "P167", "P168", "P169", "P170", "P171", "P172", "P173", "P174", "P175",
                "P184", "P185", "P186", "P187", "P188", "P189", "P190", "P191", "P192", "P193", "P194", "P195"]
operate_area = ["P100", "P101","P106", "P107","P112", "P113","P118", "P119"]
coupler_map.R_G0 = ["P100", "P101"]
coupler_map.R_G1 = ["P106", "P107"]
coupler_map.R_G2 = ["P112", "P113"]
coupler_map.R_G3 = ["P118", "P119"]

readout_error.P144 = 1.0
readout_error.P145 = 2.0
readout_error.P146 = 3.0
readout_error.P147 = 4.0
readout_error.P148 = 5.0
readout_error.P149 = 5.0
readout_error.P150 = 6.0
readout_error.P151 = 7.0
readout_error.P152 = 6.0
readout_error.P153 = 5.0
readout_error.P154 = 4.0
readout_error.P155 = 3.0
readout_error.P164 = 1.0
readout_error.P165 = 2.0
readout_error.P166 = 2.0
readout_error.P167 = 3.0
readout_error.P168 = 4.0
readout_error.P169 = 5.0
readout_error.P170 = 6.0
readout_error.P171 = 7.0
readout_error.P172 = 1.0
readout_error.P173 = 3.0
readout_error.P174 = 2.0
readout_error.P175 = 4.0
readout_error.P184 = 5.0
readout_error.P185 = 6.0
readout_error.P186 = 7.0
readout_error.P187 = 8.0
readout_error.P188 = 5.0
readout_error.P189 = 3.0
readout_error.P190 = 4.0
readout_error.P191 = 3.0
readout_error.P192 = 4.0
readout_error.P193 = 5.0
readout_error.P194 = 3.0
readout_error.P195 = 2.0

coupler_error.R_G0 = 3.0
coupler_error.R_G1 = 3.0
coupler_error.R_G2 = 3.0
coupler_error.R_G3 = 3.0

[dummy.transpiler.decomposition_rule]
# Samples
u3.params = ["a", "b", "c"]
u3.gates = [
    ["rz", [0], ["c"]],
    ["rx", [0], ["pi/2"]],
    ["rz", [0], ["b+pi"]],
    ["rx", [0], ["pi/2"]],
    ["rz", [0], ["a+pi"]]
]
h.gates = [
    ["rx", [0], ["pi/2"]]
]
