[hanyuan1]
alias_name = "中科酷原-汉原1"
driver = "DriverHanyuan1"
description = "中科酷原-汉原1(hanyuan1)"

# [Optional] max qubits of device
# device_max_qubits = 100

# [Optional] debug
# debug = false
debug = false

# [Optional] device log file path
# device_log_file = /var/log/qcos/device_hanyuan1.log
device_log_file = "/var/log/qcos/device_hanyuan1.log"

# [Optional] device manager log file path
# mgr_log_file = /var/log/qcos/device_mgr_hanyuan1.log
mgr_log_file = "/var/log/qcos/device_mgr_hanyuan1.log"

# [Optional] log format string
# log_format = "%(asctime)s | %(levelname)s | %(module)s:%(lineno)s %(message)s"

# [Optional] log rotate, max_size (MB). default: 10MB
# log_rotate_max_size_mb = 10

# [Optional] log rotate, backup count. default: 10
# log_rotate_backup_count = 10

# [Optional] log rotate, compression. default: true
# log_rotate_compression = true

# [Optional] max queued jobs, -1 means unlimited
max_queued_jobs = -1

# [Optional] max job wait time, default value is 604800 seconds (7 days)
max_job_wait_time = 604800

# [Optional] job query interval, default value is 5 seconds
job_query_interval = 5

ip_address = "127.0.0.1"
port = 18402
callback_baseurl = "http://127.0.0.1"
zmq_ip_address = "127.0.0.1"
zmq_port = 18403
use_zmq = true
zmq_pool_size = 60

[hanyuan1.device_monitor]
# [Optional] enable device monitor
enable_device_monitor = true

# [Optional] device monitor log file path
monitor_log_file = "/var/log/qcos/device_monitor_hanyuan1.log"

# [Optional] monitor polling interval (secs)
polling_interval = 60

[hanyuan1.transpiler.qpu_configs]
qubits = 6
storage_area = ["S27", "S28", "S29", "S35", "S36", "S37"]
operate_area = ["P27", "P28", "P29", "P35", "P36", "P37"]

coupler_map.G0 = ["P27", "P35"]
coupler_map.G1 = ["P28", "P36"]
coupler_map.G2 = ["P29", "P37"]
coupler_map.G3 = ["P27", "P28"]
coupler_map.G4 = ["P35", "P36"]
coupler_map.G5 = ["P28", "P29"]

readout_error.S27 = 1.0
readout_error.S28 = 2.0
readout_error.S35 = 3.0
readout_error.S36 = 4.0
readout_error.S29 = 5.0
readout_error.S37 = 6.0

coupler_error.G0 = 3.0
coupler_error.G1 = 3.0
coupler_error.G2 = 3.0
coupler_error.G3 = 3.0
coupler_error.G4 = 3.0
coupler_error.G5 = 3.0

closest.P27 = "S27"
closest.P28 = "S28"
closest.P35 = "S35"
closest.P36 = "S36"
closest.P29 = "S29"
closest.P37 = "S37"
