[lq_agate100]
alias_name = "逻辑比特 AGate-100"
driver = "DriverLqAGate100"
description = "逻辑比特 AGate-100"

# [Optional] enable or disable the device
# enable = true

# [Optional] debug
# debug = false
debug = false

# [Optional] device log file path
# device_log_file = /var/log/qcos/device_lq_agate_100.log
device_log_file = "/var/log/qcos/device_lq_agate100.log"

# [Optional] device manager log file path
# mgr_log_file = /var/log/qcos/device_mgr_lq_agate100.log

# [Optional] log format string
# log_format = "%(asctime)s | %(levelname)s | %(module)s:%(lineno)s %(message)s"

# [Optional] log rotate, max_size (MB). default: 10MB
# log_rotate_max_size_mb = 10

# [Optional] log rotate, backup count. default: 10
# log_rotate_backup_count = 10

# [Optional] log rotate, compression. default: true
# log_rotate_compression = true

# [Optional] max queued jobs, -1 means unlimited
max_queued_jobs = -1

# [Optional] max job wait time, default value is 604800 seconds (7 days)
max_job_wait_time = 604800

# [Optional] job query interval, default value is 5 seconds
job_query_interval = 5

chip_name = "AGate-100"
token = ""
url = "https://cloud.logicalqubit.com"

[lq_agate100.device_monitor]
# [Optional] enable device monitor
enable_device_monitor = true

# [Optional] device monitor log file path
monitor_log_file = "/var/log/qcos/device_monitor_lq_agate100.log"

# [Optional] monitor polling interval (secs)
polling_interval = 60

[lq_agate100.transpiler.qpu_configs]
qubits = 101

coupler_map.CZ0_1 = ["Q0", "Q1"]
coupler_map.CZ1_2 = ["Q1", "Q2"]
coupler_map.CZ2_3 = ["Q2", "Q3"]
coupler_map.CZ3_4 = ["Q3", "Q4"]
coupler_map.CZ3_36 = ["Q3", "Q36"]
coupler_map.CZ3_66 = ["Q3", "Q66"]
coupler_map.CZ4_5 = ["Q4", "Q5"]
coupler_map.CZ4_35 = ["Q4", "Q35"]
coupler_map.CZ5_6 = ["Q5", "Q6"]
coupler_map.CZ6_7 = ["Q6", "Q7"]
coupler_map.CZ6_35 = ["Q6", "Q35"]
coupler_map.CZ7_8 = ["Q7", "Q8"]
coupler_map.CZ7_28 = ["Q7", "Q28"]
coupler_map.CZ7_34 = ["Q7", "Q34"]
coupler_map.CZ8_9 = ["Q8", "Q9"]
coupler_map.CZ8_27 = ["Q8", "Q27"]
coupler_map.CZ9_10 = ["Q9", "Q10"]
coupler_map.CZ10_11 = ["Q10", "Q11"]
coupler_map.CZ10_27 = ["Q10", "Q27"]
coupler_map.CZ11_12 = ["Q11", "Q12"]
coupler_map.CZ11_18 = ["Q11", "Q18"]
coupler_map.CZ11_26 = ["Q11", "Q26"]
coupler_map.CZ12_13 = ["Q12", "Q13"]
coupler_map.CZ12_17 = ["Q12", "Q17"]
coupler_map.CZ13_14 = ["Q13", "Q14"]
coupler_map.CZ14_15 = ["Q14", "Q15"]
coupler_map.CZ14_17 = ["Q14", "Q17"]
coupler_map.CZ15_16 = ["Q15", "Q16"]
coupler_map.CZ15_86 = ["Q15", "Q86"]
coupler_map.CZ16_17 = ["Q16", "Q17"]
coupler_map.CZ16_19 = ["Q16", "Q19"]
coupler_map.CZ16_87 = ["Q16", "Q87"]
coupler_map.CZ17_18 = ["Q17", "Q18"]
coupler_map.CZ18_19 = ["Q18", "Q19"]
coupler_map.CZ18_25 = ["Q18", "Q25"]
coupler_map.CZ19_20 = ["Q19", "Q20"]
coupler_map.CZ19_24 = ["Q19", "Q24"]
coupler_map.CZ20_21 = ["Q20", "Q21"]
coupler_map.CZ20_23 = ["Q20", "Q23"]
coupler_map.CZ20_87 = ["Q20", "Q87"]
coupler_map.CZ21_22 = ["Q21", "Q22"]
coupler_map.CZ22_23 = ["Q22", "Q23"]
coupler_map.CZ22_45 = ["Q22", "Q45"]
coupler_map.CZ22_47 = ["Q22", "Q47"]
coupler_map.CZ23_24 = ["Q23", "Q24"]
coupler_map.CZ24_25 = ["Q24", "Q25"]
coupler_map.CZ25_26 = ["Q25", "Q26"]
coupler_map.CZ25_30 = ["Q25", "Q30"]
coupler_map.CZ26_27 = ["Q26", "Q27"]
coupler_map.CZ26_29 = ["Q26", "Q29"]
coupler_map.CZ27_28 = ["Q27", "Q28"]
coupler_map.CZ28_29 = ["Q28", "Q29"]
coupler_map.CZ28_33 = ["Q28", "Q33"]
coupler_map.CZ29_30 = ["Q29", "Q30"]
coupler_map.CZ29_32 = ["Q29", "Q32"]
coupler_map.CZ30_31 = ["Q30", "Q31"]
coupler_map.CZ31_32 = ["Q31", "Q32"]
coupler_map.CZ31_40 = ["Q31", "Q40"]
coupler_map.CZ31_42 = ["Q31", "Q42"]
coupler_map.CZ32_33 = ["Q32", "Q33"]
coupler_map.CZ32_39 = ["Q32", "Q39"]
coupler_map.CZ33_34 = ["Q33", "Q34"]
coupler_map.CZ33_38 = ["Q33", "Q38"]
coupler_map.CZ34_35 = ["Q34", "Q35"]
coupler_map.CZ34_37 = ["Q34", "Q37"]
coupler_map.CZ35_36 = ["Q35", "Q36"]
coupler_map.CZ36_37 = ["Q36", "Q37"]
coupler_map.CZ36_65 = ["Q36", "Q65"]
coupler_map.CZ37_38 = ["Q37", "Q38"]
coupler_map.CZ37_64 = ["Q37", "Q64"]
coupler_map.CZ38_39 = ["Q38", "Q39"]
coupler_map.CZ38_63 = ["Q38", "Q63"]
coupler_map.CZ39_40 = ["Q39", "Q40"]
coupler_map.CZ39_62 = ["Q39", "Q62"]
coupler_map.CZ40_41 = ["Q40", "Q41"]
coupler_map.CZ40_61 = ["Q40", "Q61"]
coupler_map.CZ41_42 = ["Q41", "Q42"]
coupler_map.CZ41_58 = ["Q41", "Q58"]
coupler_map.CZ41_60 = ["Q41", "Q60"]
coupler_map.CZ42_43 = ["Q42", "Q43"]
coupler_map.CZ42_88 = ["Q42", "Q88"]
coupler_map.CZ43_44 = ["Q43", "Q44"]
coupler_map.CZ43_58 = ["Q43", "Q58"]
coupler_map.CZ44_45 = ["Q44", "Q45"]
coupler_map.CZ44_57 = ["Q44", "Q57"]
coupler_map.CZ45_46 = ["Q45", "Q46"]
coupler_map.CZ46_47 = ["Q46", "Q47"]
coupler_map.CZ46_51 = ["Q46", "Q51"]
coupler_map.CZ47_48 = ["Q47", "Q48"]
coupler_map.CZ48_49 = ["Q48", "Q49"]
coupler_map.CZ48_51 = ["Q48", "Q51"]
coupler_map.CZ49_50 = ["Q49", "Q50"]
coupler_map.CZ50_51 = ["Q50", "Q51"]
coupler_map.CZ51_52 = ["Q51", "Q52"]
coupler_map.CZ52_53 = ["Q52", "Q53"]
coupler_map.CZ52_55 = ["Q52", "Q55"]
coupler_map.CZ53_54 = ["Q53", "Q54"]
coupler_map.CZ54_55 = ["Q54", "Q55"]
coupler_map.CZ55_56 = ["Q55", "Q56"]
coupler_map.CZ55_89 = ["Q55", "Q89"]
coupler_map.CZ56_57 = ["Q56", "Q57"]
coupler_map.CZ57_58 = ["Q57", "Q58"]
coupler_map.CZ57_91 = ["Q57", "Q91"]
coupler_map.CZ58_59 = ["Q58", "Q59"]
coupler_map.CZ59_60 = ["Q59", "Q60"]
coupler_map.CZ59_74 = ["Q59", "Q74"]
coupler_map.CZ59_91 = ["Q59", "Q91"]
coupler_map.CZ60_61 = ["Q60", "Q61"]
coupler_map.CZ60_73 = ["Q60", "Q73"]
coupler_map.CZ61_72 = ["Q61", "Q72"]
coupler_map.CZ62_63 = ["Q62", "Q63"]
coupler_map.CZ62_71 = ["Q62", "Q71"]
coupler_map.CZ63_64 = ["Q63", "Q64"]
coupler_map.CZ63_70 = ["Q63", "Q70"]
coupler_map.CZ64_65 = ["Q64", "Q65"]
coupler_map.CZ64_69 = ["Q64", "Q69"]
coupler_map.CZ65_66 = ["Q65", "Q66"]
coupler_map.CZ65_68 = ["Q65", "Q68"]
coupler_map.CZ66_67 = ["Q66", "Q67"]
coupler_map.CZ67_68 = ["Q67", "Q68"]
coupler_map.CZ68_69 = ["Q68", "Q69"]
coupler_map.CZ69_70 = ["Q69", "Q70"]
coupler_map.CZ69_80 = ["Q69", "Q80"]
coupler_map.CZ70_71 = ["Q70", "Q71"]
coupler_map.CZ70_79 = ["Q70", "Q79"]
coupler_map.CZ71_72 = ["Q71", "Q72"]
coupler_map.CZ71_78 = ["Q71", "Q78"]
coupler_map.CZ72_73 = ["Q72", "Q73"]
coupler_map.CZ72_77 = ["Q72", "Q77"]
coupler_map.CZ73_74 = ["Q73", "Q74"]
coupler_map.CZ73_76 = ["Q73", "Q76"]
coupler_map.CZ74_75 = ["Q74", "Q75"]
coupler_map.CZ74_90 = ["Q74", "Q90"]
coupler_map.CZ75_76 = ["Q75", "Q76"]
coupler_map.CZ75_93 = ["Q75", "Q93"]
coupler_map.CZ76_77 = ["Q76", "Q77"]
coupler_map.CZ76_95 = ["Q76", "Q95"]
coupler_map.CZ77_78 = ["Q77", "Q78"]
coupler_map.CZ78_79 = ["Q78", "Q79"]
coupler_map.CZ78_94 = ["Q78", "Q94"]
coupler_map.CZ79_80 = ["Q79", "Q80"]
coupler_map.CZ79_82 = ["Q79", "Q82"]
coupler_map.CZ80_81 = ["Q80", "Q81"]
coupler_map.CZ81_82 = ["Q81", "Q82"]
coupler_map.CZ81_84 = ["Q81", "Q84"]
coupler_map.CZ82_83 = ["Q82", "Q83"]
coupler_map.CZ82_94 = ["Q82", "Q94"]
coupler_map.CZ83_84 = ["Q83", "Q84"]
coupler_map.CZ84_85 = ["Q84", "Q85"]
coupler_map.CZ90_91 = ["Q90", "Q91"]
coupler_map.CZ90_92 = ["Q90", "Q92"]
coupler_map.CZ95_96 = ["Q95", "Q96"]
coupler_map.CZ95_100 = ["Q95", "Q100"]
coupler_map.CZ96_97 = ["Q96", "Q97"]
coupler_map.CZ96_99 = ["Q96", "Q99"]
coupler_map.CZ97_98 = ["Q97", "Q98"]
coupler_map.CZ98_99 = ["Q98", "Q99"]
coupler_map.CZ1_57 = ["Q1", "Q57"]
coupler_map.CZ1_58 = ["Q1", "Q58"]

readout_error.Q0 = 0.0265
readout_error.Q1 = 0.0245
readout_error.Q2 = 0.0175
readout_error.Q3 = 0.0115
readout_error.Q4 = 0.013
readout_error.Q5 = 0.012
readout_error.Q6 = 0.0155
readout_error.Q7 = 0.024
readout_error.Q8 = 0.011
readout_error.Q9 = 0.024
readout_error.Q10 = 0.008
readout_error.Q11 = 0.0125
readout_error.Q12 = 0.0095
readout_error.Q13 = 0.0185
readout_error.Q14 = 0.008
readout_error.Q15 = 0.0155
readout_error.Q16 = 0.022
readout_error.Q17 = 0.012
readout_error.Q18 = 0.011
readout_error.Q19 = 0.01
readout_error.Q20 = 0.016
readout_error.Q21 = 0.0115
readout_error.Q22 = 0.0135
readout_error.Q23 = 0.0145
readout_error.Q24 = 0.0185
readout_error.Q25 = 0.025
readout_error.Q26 = 0.0215
readout_error.Q27 = 0.019
readout_error.Q28 = 0.014
readout_error.Q29 = 0.0225
readout_error.Q30 = 0.0225
readout_error.Q31 = 0.0215
readout_error.Q32 = 0.0075
readout_error.Q33 = 0.017
readout_error.Q34 = 0.017
readout_error.Q35 = 0.019
readout_error.Q36 = 0.022
readout_error.Q37 = 0.0135
readout_error.Q38 = 0.02
readout_error.Q39 = 0.0435
readout_error.Q40 = 0.044
readout_error.Q41 = 0.0125
readout_error.Q42 = 0.013
readout_error.Q43 = 0.0425
readout_error.Q44 = 0.0105
readout_error.Q45 = 0.01
readout_error.Q46 = 0.0165
readout_error.Q47 = 0.007
readout_error.Q48 = 0.033
readout_error.Q49 = 0.035
readout_error.Q50 = 0.0355
readout_error.Q51 = 0.0145
readout_error.Q52 = 0.152
readout_error.Q53 = 0.0185
readout_error.Q54 = 0.033
readout_error.Q55 = 0.014
readout_error.Q56 = 0.0165
readout_error.Q57 = 0.026
readout_error.Q58 = 0.013
readout_error.Q59 = 0.059
readout_error.Q60 = 0.03
readout_error.Q61 = 0.0105
readout_error.Q62 = 0.0175
readout_error.Q63 = 0.027
readout_error.Q64 = 0.027
readout_error.Q65 = 0.01
readout_error.Q66 = 0.0165
readout_error.Q67 = 0.0095
readout_error.Q68 = 0.0235
readout_error.Q69 = 0.0435
readout_error.Q70 = 0.02
readout_error.Q71 = 0.0135
readout_error.Q72 = 0.013
readout_error.Q73 = 0.021
readout_error.Q74 = 0.0295
readout_error.Q75 = 0.022
readout_error.Q76 = 0.019
readout_error.Q77 = 0.0135
readout_error.Q78 = 0.0445
readout_error.Q79 = 0.0125
readout_error.Q80 = 0.053
readout_error.Q81 = 0.0285
readout_error.Q82 = 0.015
readout_error.Q83 = 0.0095
readout_error.Q84 = 0.0275
readout_error.Q85 = 0.013
readout_error.Q86 = 0.0195
readout_error.Q87 = 0.0295
readout_error.Q88 = 0.0685
readout_error.Q89 = 0.018
readout_error.Q90 = 0.024
readout_error.Q91 = 0.03
readout_error.Q92 = 0.037
readout_error.Q93 = 0.0945
readout_error.Q94 = 0.0175
readout_error.Q95 = 0.023
readout_error.Q96 = 0.062
readout_error.Q97 = 0.0245
readout_error.Q98 = 0.045
readout_error.Q99 = 0.0135
readout_error.Q100 = 0.0755

coupler_error.CZ0_1 = 0.0054
coupler_error.CZ1_2 = 0.006
coupler_error.CZ2_3 = 0.0077
coupler_error.CZ3_4 = 0.0031
coupler_error.CZ3_36 = 0.0043
coupler_error.CZ3_66 = 0.0053
coupler_error.CZ4_5 = 0.0052
coupler_error.CZ4_35 = 0.0122
coupler_error.CZ5_6 = 0.0074
coupler_error.CZ6_7 = 0.0089
coupler_error.CZ6_35 = 0.0165
coupler_error.CZ7_8 = 0.0067
coupler_error.CZ7_28 = 0.0392
coupler_error.CZ7_34 = 0.0061
coupler_error.CZ8_9 = 0.0022
coupler_error.CZ8_27 = 0.0063
coupler_error.CZ9_10 = 0.005
coupler_error.CZ10_11 = 0.0115
coupler_error.CZ10_27 = 0.0101
coupler_error.CZ11_12 = 0.003
coupler_error.CZ11_18 = 0.0099
coupler_error.CZ11_26 = 0.0087
coupler_error.CZ12_13 = 0.012
coupler_error.CZ12_17 = 0.0228
coupler_error.CZ13_14 = 0.0095
coupler_error.CZ14_15 = 0.0028
coupler_error.CZ14_17 = 0.0106
coupler_error.CZ15_16 = 0.0028
coupler_error.CZ15_86 = 0.0035
coupler_error.CZ16_17 = 0.0132
coupler_error.CZ16_19 = 0.004
coupler_error.CZ16_87 = 0.0038
coupler_error.CZ17_18 = 0.0141
coupler_error.CZ18_19 = 0.0108
coupler_error.CZ18_25 = 0.007
coupler_error.CZ19_20 = 0.007
coupler_error.CZ19_24 = 0.0177
coupler_error.CZ20_21 = 0.0075
coupler_error.CZ20_23 = 0.0139
coupler_error.CZ20_87 = 0.005
coupler_error.CZ21_22 = 0.0042
coupler_error.CZ22_23 = 0.0101
coupler_error.CZ22_45 = 0.0026
coupler_error.CZ22_47 = 0.0024
coupler_error.CZ23_24 = 0.008
coupler_error.CZ24_25 = 0.0152
coupler_error.CZ25_26 = 0.009
coupler_error.CZ25_30 = 0.0124
coupler_error.CZ26_27 = 0.0062
coupler_error.CZ26_29 = 0.0062
coupler_error.CZ27_28 = 0.0047
coupler_error.CZ28_29 = 0.0054
coupler_error.CZ28_33 = 0.0043
coupler_error.CZ29_30 = 0.0046
coupler_error.CZ29_32 = 0.0057
coupler_error.CZ30_31 = 0.005
coupler_error.CZ31_32 = 0.0053
coupler_error.CZ31_40 = 0.004
coupler_error.CZ31_42 = 0.0041
coupler_error.CZ32_33 = 0.0055
coupler_error.CZ32_39 = 0.0065
coupler_error.CZ33_34 = 0.0133
coupler_error.CZ33_38 = 0.0036
coupler_error.CZ34_35 = 0.0133
coupler_error.CZ34_37 = 0.0065
coupler_error.CZ35_36 = 0.0076
coupler_error.CZ36_37 = 0.005
coupler_error.CZ36_65 = 0.0054
coupler_error.CZ37_38 = 0.0034
coupler_error.CZ37_64 = 0.0042
coupler_error.CZ38_39 = 0.0039
coupler_error.CZ38_63 = 0.0027
coupler_error.CZ39_40 = 0.0047
coupler_error.CZ39_62 = 0.0064
coupler_error.CZ40_41 = 0.0047
coupler_error.CZ40_61 = 0.0047
coupler_error.CZ41_42 = 0.01
coupler_error.CZ41_58 = 0.0089
coupler_error.CZ41_60 = 0.0108
coupler_error.CZ42_43 = 0.0067
coupler_error.CZ42_88 = 0.005
coupler_error.CZ43_44 = 0.005
coupler_error.CZ43_58 = 0.0099
coupler_error.CZ44_45 = 0.0069
coupler_error.CZ44_57 = 0.0084
coupler_error.CZ45_46 = 0.0066
coupler_error.CZ46_47 = 0.0169
coupler_error.CZ46_51 = 0.0108
coupler_error.CZ47_48 = 0.0055
coupler_error.CZ48_49 = 0.0032
coupler_error.CZ48_51 = 0.0028
coupler_error.CZ49_50 = 0.0041
coupler_error.CZ50_51 = 0.0058
coupler_error.CZ51_52 = 0.0055
coupler_error.CZ52_53 = 0.0106
coupler_error.CZ52_55 = 0.0014
coupler_error.CZ53_54 = 0.0076
coupler_error.CZ54_55 = 0.0062
coupler_error.CZ55_56 = 0.0057
coupler_error.CZ55_89 = 0.014
coupler_error.CZ56_57 = 0.005
coupler_error.CZ57_58 = 0.0052
coupler_error.CZ57_91 = 0.0076
coupler_error.CZ58_59 = 0.0073
coupler_error.CZ59_60 = 0.0114
coupler_error.CZ59_74 = 0.0071
coupler_error.CZ59_91 = 0.0097
coupler_error.CZ60_61 = 0.0094
coupler_error.CZ60_73 = 0.0082
coupler_error.CZ61_72 = 0.0054
coupler_error.CZ62_63 = 0.0157
coupler_error.CZ62_71 = 0.0105
coupler_error.CZ63_64 = 0.0091
coupler_error.CZ63_70 = 0.0095
coupler_error.CZ64_65 = 0.0056
coupler_error.CZ64_69 = 0.0063
coupler_error.CZ65_66 = 0.0031
coupler_error.CZ65_68 = 0.0031
coupler_error.CZ66_67 = 0.006
coupler_error.CZ67_68 = 0.0051
coupler_error.CZ68_69 = 0.0042
coupler_error.CZ69_70 = 0.0032
coupler_error.CZ69_80 = 0.0073
coupler_error.CZ70_71 = 0.005
coupler_error.CZ70_79 = 0.0079
coupler_error.CZ71_72 = 0.0068
coupler_error.CZ71_78 = 0.0054
coupler_error.CZ72_73 = 0.0058
coupler_error.CZ72_77 = 0.005
coupler_error.CZ73_74 = 0.0049
coupler_error.CZ73_76 = 0.0064
coupler_error.CZ74_75 = 0.0064
coupler_error.CZ74_90 = 0.0222
coupler_error.CZ75_76 = 0.0043
coupler_error.CZ75_93 = 0.0097
coupler_error.CZ76_77 = 0.004
coupler_error.CZ76_95 = 0.0066
coupler_error.CZ77_78 = 0.0035
coupler_error.CZ78_79 = 0.0034
coupler_error.CZ78_94 = 0.004
coupler_error.CZ79_80 = 0.0034
coupler_error.CZ79_82 = 0.0035
coupler_error.CZ80_81 = 0.0068
coupler_error.CZ81_82 = 0.0032
coupler_error.CZ81_84 = 0.0048
coupler_error.CZ82_83 = 0.0027
coupler_error.CZ82_94 = 0.0052
coupler_error.CZ83_84 = 0.0028
coupler_error.CZ84_85 = 0.006
coupler_error.CZ90_91 = 0.0092
coupler_error.CZ90_92 = 0.0185
coupler_error.CZ95_96 = 0.0033
coupler_error.CZ95_100 = 0.0078
coupler_error.CZ96_97 = 0.003
coupler_error.CZ96_99 = 0.0019
coupler_error.CZ97_98 = 0.0042
coupler_error.CZ98_99 = 0.0077
coupler_error.CZ1_57 = 0.0075
coupler_error.CZ1_58 = 0.0149