[qiskit_aer_sim]
alias_name = "IBM-Qiskit-Aer模拟器"
driver = "DriverQiskitAerSim"
description = "IBM-Qiskit-Aer模拟器(qiskit-aer-sim)"

# [Optional] max qubits of device
# device_max_qubits = 10

# [Optional] debug
# debug = false
debug = false

# [Optional] device log file path
# device_log_file = /var/log/qcos/device_qiskit_aer_sim.log
device_log_file = "/var/log/qcos/device_qiskit_aer_sim.log"

# [Optional] device manager log file path
# mgr_log_file = /var/log/qcos/device_mgr_qiskit_aer_sim.log

# [Optional] log format string
# log_format = "%(asctime)s | %(levelname)s | %(module)s:%(lineno)s %(message)s"

# [Optional] log rotate, max_size (MB). default: 10MB
# log_rotate_max_size_mb = 10

# [Optional] log rotate, backup count. default: 10
# log_rotate_backup_count = 10

# [Optional] log rotate, compression. default: true
# log_rotate_compression = true

# [Optional] max queued jobs, -1 means unlimited
max_queued_jobs = -1

[qiskit_aer_sim.device_monitor]
# [Optional] enable device monitor
enable_device_monitor = false

# [Optional] device monitor log file path
monitor_log_file = "/var/log/qcos/device_monitor_qiskit_aer_sim.log"

# [Optional] monitor polling interval (secs)
polling_interval = 60
