[spinq_gemini]
alias_name = "量旋科技-双子座核磁量子计算机"
driver = "DriverSpinQGemini"
description = "量旋科技-双子座核磁量子计算机"

# [Optional] max qubits of device
# device_max_qubits = 100

# [Optional] debug
# debug = false
debug = false

# [Optional] device log file path
# device_log_file = /var/log/qcos/device_spinq_gemini.log
device_log_file = "/var/log/qcos/device_spinq_gemini.log"

# [Optional] enable device monitor
# enable_device_monitor = false
enable_device_monitor = false

# [Optional] device monitor log file path
# monitor_log_file = /var/log/qcos/device_montior_spinq_gemini.log
monitor_log_file = "/var/log/qcos/device_monitor_spinq_gemini.log"

# [Optional] device manager log file path
# mgr_log_file = /var/log/qcos/device_mgr_spinq_gemini.log
# [Optional] log format string
# log_format = "%(asctime)s | %(levelname)s | %(module)s:%(lineno)s %(message)s"

# [Optional] log rotate, max_size (MB). default: 10MB
# log_rotate_max_size_mb = 10

# [Optional] log rotate, backup count. default: 10
# log_rotate_backup_count = 10

# [Optional] log rotate, compression. default: true
# log_rotate_compression = true

# [Optional] max queued jobs, -1 means unlimited
max_queued_jobs = -1

# [Optional] remote host
remote_host = "cloud.spinq.cn"

# [Optional] remote port
remote_port = 6060

# [Required] user name
username = "spinq_visitor_002"

# [Required] key file content
signature = ""

# [Optional] max job wait time, default value is 604800 seconds (7 days)
max_job_wait_time = 604800

# [Optional] job query interval, default value is 5 seconds
job_query_interval = 5

[spinq_gemini.transpiler.qpu_configs]
qubits = 2
coupler_map.CX1_2 = ["Q1", "Q2"]
coupler_map.CX2_1 = ["Q2", "Q1"]
