[tiangong550_v2]
alias_name = "玻色量子-天工550"
driver = "DriverTiangong550V2"
description = "玻色量子-天工(tiangong550_v2)"

# [Optional] max qubits of device
# device_max_qubits = 100

# [Optional] debug
# debug = false
debug = false

# [Optional] device log file path
# device_log_file = /var/log/qcos/device_tiangong550_v2.log
device_log_file = "/var/log/qcos/device_tiangong550_v2.log"

# [Optional] device monitor log file path
# monitor_log_file = /var/log/qcos/device_montior_tiangong550_v2.log
monitor_log_file = "/var/log/qcos/device_monitor_tiangong550_v2.log"

# [Optional] device manager log file path
# mgr_log_file = /var/log/qcos/device_mgr_tiangong550_v2.log
# [Optional] log format string
# log_format = "%(asctime)s | %(levelname)s | %(module)s:%(lineno)s %(message)s"

# [Optional] log rotate, max_size (MB). default: 10MB
# log_rotate_max_size_mb = 10

# [Optional] log rotate, backup count. default: 10
# log_rotate_backup_count = 10

# [Optional] log rotate, compression. default: true
# log_rotate_compression = true

# [Optional] max queued jobs, -1 means unlimited
max_queued_jobs = -1

# Backend configs
# [Required] user id
user_id = "000000000000001"
# [Required] sdk code
password_sdk_code = ""

# [Required] machine name
machine_name = "CPQC-550"

domain_url_auth = "https://open.qboson.com"
domain_url_task = "https://new-open.qboson.com"
