[wy_hanyuan1]
alias_name = "WY-中科酷原-汉原1"
driver = "DriverWuyueHanyuan1"
description = "WY-中科酷原-汉原1(wy_hanyuan1)"

# [Optional] max qubits of device
# device_max_qubits = 100

# [Optional] debug
# debug = false
debug = false

# [Optional] device log file path
# device_log_file = /var/log/qcos/device_wy_hanyuan1.log
device_log_file = "/var/log/qcos/device_wy_hanyuan1.log"

# [Optional] enable device monitor
# enable_device_monitor = false
enable_device_monitor = false

# [Optional] device monitor log file path
# monitor_log_file = /var/log/qcos/device_montior_wy_hanyuan1.log
monitor_log_file = "/var/log/qcos/device_monitor_wy_hanyuan1.log"

# [Optional] device manager log file path
# mgr_log_file = /var/log/qcos/device_mgr_wy_hanyuan1.log
# [Optional] log format string
# log_format = "%(asctime)s | %(levelname)s | %(module)s:%(lineno)s %(message)s"

# [Optional] log rotate, max_size (MB). default: 10MB
# log_rotate_max_size_mb = 10

# [Optional] log rotate, backup count. default: 10
# log_rotate_backup_count = 10

# [Optional] log rotate, compression. default: true
# log_rotate_compression = true

# [Optional] max queued jobs, -1 means unlimited
max_queued_jobs = -1

# [Optional] max job wait time, default value is 604800 seconds (7 days)
max_job_wait_time = 604800

# [Optional] job query interval, default value is 5 seconds
job_query_interval = 5

ip_address = "127.0.0.1"
port = 8181
client_id = "12345678"
eng_code = "12345678"
password_secret = ""
password_pub_key = ""
password_pri_key = ""