# ----------------------------------------------------------------------
# Copyright© 2025 China Mobile (SuZhou) Software Technology Co.,Ltd.
#
# qcos is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions
# of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#         http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.
# ----------------------------------------------------------------------

version: '3'
services:
  prefect-server:
    image: ${REGISTRY}${PREFECT_IMAGE_NAME}:${PREFECT_IMAGE_VERSION}
    restart: always
    command: prefect server start
    network_mode: "host"
    environment:
      PREFECT_SERVER_API_HOST: ${PREFECT_SERVER_API_HOST}
      PREFECT_SERVER_DATABASE_CONNECTION_URL: "sqlite+aiosqlite:////var/qcos/db/prefect.db"
      PREFECT_API_URL: "http://${PREFECT_SERVER_API_HOST}:4200/api"
      PREFECT_RESULTS_PERSIST_BY_DEFAULT: true
      PREFECT_LOCAL_STORAGE_PATH: /var/qcos/storage
    volumes:
      - /var/qcos/storage:/var/qcos/storage
      - /var/qcos/db:/var/qcos/db
      - code-data:/root/qcos

  qcos-dev:
    container_name: qcos-dev
    image: ${REGISTRY}${QCOS_IMAGE_NAME}:${QCOS_IMAGE_VERSION}
    privileged: true
    network_mode: "host"
    restart: always
    stdin_open: True
    tty: True
    depends_on:
      - prefect-server
    environment:
      - DEBUG=${DEBUG}
      - QCOS_CONTAINER_NAME=${QCOS_CONTAINER_NAME}
      - PYTHONPATH=/root/
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    volumes:
      - /etc/hosts:/etc/hosts
      - /etc/timezone:/etc/timezone
      - /etc/localtime:/etc/localtime
      - /etc/qcos:/etc/qcos
      - /var/log/qcos:/var/log/qcos
      - /var/run/qcos:/var/run/qcos
      - ${QCOS_LOCAL_SRC_DIR}/qcos:/root/qcos
      - ${QCOS_LOCAL_SRC_DIR}/bin/qcos.py:/usr/bin/qcos
      - code-data:/root/qcos
    entrypoint: /entrypoint.sh
volumes:
  code-data: {}
