# ----------------------------------------------------------------------
# Copyright© 2025 China Mobile (SuZhou) Software Technology Co.,Ltd.
#
# qcos is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions
# of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#         http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.
# ----------------------------------------------------------------------

version: '3'
services:
  prefect-server:
    container_name: prefect-server
    image: ${REGISTRY}${PREFECT_IMAGE_NAME}:${PREFECT_IMAGE_VERSION}
    restart: always
    command: prefect server start
    network_mode: "host"
    environment:
      TZ: Asia/Shanghai
      PREFECT_SERVER_API_HOST: ${PREFECT_SERVER_API_HOST}
      PREFECT_SERVER_DATABASE_CONNECTION_URL: "sqlite+aiosqlite:////var/qcos/db/prefect.db"
      PREFECT_API_URL: "http://${PREFECT_SERVER_API_HOST}:4200/api"
      PREFECT_LOCAL_STORAGE_PATH: /var/qcos/storage
      PREFECT_API_DEFAULT_LIMIT: 100000
    volumes:
      - /etc/hosts:/etc/hosts
      - /var/log/qcos:/var/log/qcos
      - /var/qcos:/var/qcos
      - /etc/qcos/prefect:/root/.prefect
      - code-data:/root/qcos
  qcos:
    container_name: qcos
    image: ${REGISTRY}${QCOS_IMAGE_NAME}:${QCOS_IMAGE_VERSION}
    privileged: true
    network_mode: "host"
    restart: always
    stdin_open: True
    depends_on:
      - prefect-server
    tty: True
    working_dir: /root
    environment:
      DEBUG: ${DEBUG}
      DEV: ${DEV}
      TZ: Asia/Shanghai
      QCOS_CONTAINER_NAME: ${QCOS_CONTAINER_NAME}
      PREFECT_SERVER_API_HOST: ${PREFECT_SERVER_API_HOST}
      PREFECT_SERVER_DATABASE_CONNECTION_URL: "sqlite+aiosqlite:///var/qcos/db/prefect.db"
      PREFECT_API_URL: "http://${PREFECT_SERVER_API_HOST}:4200/api"
      PREFECT_LOCAL_STORAGE_PATH: /var/qcos/storage
      PREFECT_LOGGING_ENABLED: ${PREFECT_LOGGING_ENABLED:-true}
      PREFECT_LOGGING_LEVEL: ${PREFECT_LOGGING_LEVEL:-INFO}
      PREFECT_LOGGING_ROOT_LEVEL: INFO
      PREFECT_LOGGING_ROOT_HANDLERS: ${PREFECT_LOGGING_ROOT_HANDLERS:-[]}
      PYTHONPATH: /root/qcos-project
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    volumes:
      - /etc/hosts:/etc/hosts
      - /etc/qcos:/etc/qcos
      - /var/log/qcos:/var/log/qcos
      - /var/run/qcos:/var/run/qcos
      - /var/qcos:/var/qcos
      - code-data:/root/qcos
    entrypoint: /entrypoint.sh
volumes:
  code-data: {}
