# ----------------------------------------------------------------------
# Copyright© 2024-2025 China Mobile (SuZhou) Software Technology Co.,Ltd.
#
# qcos is licensed under Mulan PSL v2.
# You can use this software according to the terms and conditions
# of the Mulan PSL v2.
# You may obtain a copy of Mulan PSL v2 at:
#         http://license.coscl.org.cn/MulanPSL2
# THIS SOFTWARE IS PROVIDED ON AN "AS IS" BASIS, WITHOUT WARRANTIES OF ANY KIND,
# EITHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO NON-INFRINGEMENT,
# MERCHANTABILITY OR FIT FOR A PARTICULAR PURPOSE.
# See the Mulan PSL v2 for more details.
# ----------------------------------------------------------------------

version: '3'
services:
  prefect-server:
    container_name: prefect-server
    image: ${REGISTRY}${PREFECT_IMAGE_NAME}:${PREFECT_IMAGE_VERSION}
    restart: always
    command: /bin/sh -c 'prefect server start'
    network_mode: "host"
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /var/tmp
    environment:
      TZ: Asia/Shanghai
      PREFECT_SERVER_API_HOST: ${PREFECT_SERVER_API_HOST}
      PREFECT_SERVER_DATABASE_CONNECTION_URL: ${PREFECT_SERVER_DATABASE_CONNECTION_URL}
      PREFECT_SERVER_ANALYTICS_ENABLED: "false"
      PREFECT_API_DATABASE_TIMEOUT: "30"
      PREFECT_API_URL: "${PREFECT_API_URL}"
      PREFECT_API_DEFAULT_LIMIT: "200"
      PREFECT_TASKS_DISABLE_CACHING: "true"
      PREFECT_RESULTS_PERSIST_BY_DEFAULT: "false"
      PREFECT_SERVER_EVENTS_RETENTION_PERIOD: "PT1H"
      # job cancel signal requires PREFECT_SERVER_EVENTS_STREAM_OUT_ENABLED=true
      PREFECT_SERVER_EVENTS_STREAM_OUT_ENABLED: "true"
      PREFECT_SERVER_SERVICES_EVENT_PERSISTER_QUEUE_MAX_SIZE: "5000"
      PREFECT_SERVER_EVENTS_RELATED_RESOURCE_CACHE_TTL: "PT150S"
      # prefect docket configs
      PREFECT_SERVER_DOCKET_URL: "redis://${REDIS_SERVER_IP}:${REDIS_SERVER_PORT}/1"
      # prefect event messaging configs
      # PREFECT_SERVER_EVENTS_MESSAGING_BROKER: "prefect_redis.messaging"
      # PREFECT_SERVER_EVENTS_MESSAGING_CACHE: "prefect_redis.messaging"
      # PREFECT_SERVER_EVENTS_CAUSAL_ORDERING: "prefect_redis.causal_ordering"
      # PREFECT_SERVER_CONCURRENCY_LEASE_STORAGE: "prefect_redis.lease_storage"
      # PREFECT_REDIS_MESSAGING_HOST: "${REDIS_SERVER_IP}"
      # PREFECT_REDIS_MESSAGING_PORT: "${REDIS_SERVER_PORT}"
      # PREFECT_REDIS_MESSAGING_DB: "1"
      # PREFECT_REDIS_EVENTS_HOST: "${REDIS_SERVER_PORT}"
      # PREFECT_REDIS_EVENTS_PORT: "${REDIS_SERVER_PORT}"
      # PREFECT_REDIS_EVENTS_DB: "1"
      PREFECT_UI_STATIC_DIRECTORY: "/tmp/prefect_ui_static"
      PYTHONPATH: /root/qcos-project/src
    volumes:
      - /etc/hosts:/etc/hosts
      - /var/log/qcos:/var/log/qcos
      - /var/qcos:/var/qcos
      - /etc/qcos/prefect:/root/.prefect
  redis:
    image: ${REGISTRY}${REDIS_IMAGE_NAME}:${REDIS_IMAGE_VERSION}
    container_name: redis
    restart: always
    network_mode: "host"
    command: redis-server --bind ${REDIS_SERVER_LISTEN_IP}
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
  qcos:
    container_name: qcos
    image: ${REGISTRY}${QCOS_REGISTRY}${QCOS_IMAGE_NAME}:${QCOS_IMAGE_VERSION}
    network_mode: "host"
    restart: always
    stdin_open: True
    depends_on:
      - prefect-server
      - redis
    tty: True
    read_only: true
    security_opt:
      - no-new-privileges:true
    tmpfs:
      - /tmp
      - /var/tmp
    working_dir: /root
    environment:
      DEBUG: ${DEBUG}
      DEV: ${DEV}
      TZ: Asia/Shanghai
      CONTAINER_NAME: ${QCOS_CONTAINER_NAME}
      API_SERVER_LISTEN_IP: ${API_SERVER_LISTEN_IP}
      API_SERVER_LISTEN_PORT: ${API_SERVER_LISTEN_PORT}
      QCOS_SERVER_IP: ${QCOS_SERVER_IP}
      QCOS_SERVER_PORT: ${QCOS_SERVER_PORT}
      QCOS_AUTH_MODE: ${QCOS_AUTH_MODE}
      QCOS_DATABASE_CONNECTION_URL: ${QCOS_DATABASE_CONNECTION_URL:-sqlite:////var/qcos/db/qcos.db?timeout=30&journal_mode=WAL}
      QCOS_VIRTUAL_INSTANCE_ID: ${QCOS_VIRTUAL_INSTANCE_ID}
      DEVICE_LIST: ${DEVICE_LIST}
      MAX_JOBS: ${MAX_JOBS}
      MAX_QUEUED_JOBS: ${MAX_QUEUED_JOBS}
      MAX_JOBS_PER_USER: ${MAX_JOBS_PER_USER}
      PASSWORD_SALT: ${PASSWORD_SALT}
      LOCAL_CICD: ${LOCAL_CICD}
      PREFECT_API_URL: ${PREFECT_API_URL:-http://127.0.0.1:4200/api}
      PREFECT_SERVER_DATABASE_CONNECTION_URL: ${PREFECT_SERVER_DATABASE_CONNECTION_URL:-sqlite+aiosqlite:////var/qcos/db/prefect.db?timeout=30&journal_mode=WAL}
      PREFECT_LOCAL_STORAGE_PATH: ${PREFECT_LOCAL_STORAGE_PATH:-/var/qcos/storage}
      PREFECT_WORKER_QUERY_SECONDS: ${PREFECT_WORKER_QUERY_SECONDS:-1}
      PREFECT_WORKER_PREFETCH_SECONDS: ${PREFECT_WORKER_PREFETCH_SECONDS:-1}
      PREFECT_WORKER_HEARTBEAT_SECONDS: ${PREFECT_WORKER_HEARTBEAT_SECONDS:-30}
      PREFECT_LOGGING_LEVEL: ${PREFECT_LOGGING_LEVEL:-INFO}
      REDIS_SERVER_IP: ${REDIS_SERVER_IP}
      REDIS_SERVER_PORT: ${REDIS_SERVER_PORT}
    command: "--db-migration --no-exit -w http://${PREFECT_SERVER_API_HOST:-127.0.0.1}:${PREFECT_SERVER_PORT}/api"
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "10"
    volumes:
      - /etc/hosts:/etc/hosts
      - /etc/qcos:/etc/qcos
      - /var/log/qcos:/var/log/qcos
      - /var/run/qcos:/var/run/qcos
      - /var/qcos:/var/qcos
    entrypoint: /entrypoint.sh
