[ST_API_SERVER]
ST_API_SERVER_IP = "127.0.0.1"
ST_API_SERVER_PORT = 18400

[DEVICES]
# override DEVICE_LIST in qcos.toml for ST tests
DEVICE_LIST = ["dummy", "tiangong100", "tiangong100_v2", "spinq_rpc", "spinq_gemini", "spinq_triangulum", "uqc_matrix2", "qutip_sim", "ciqtek_ion_1"]