# for development purpose
# QCOS configures
[DEFAULT]
DEBUG = false
# max jobs (all status) [GLOBAL CONFIG]
MAX_JOBS = 10000
# max queued+running jobs [GLOBAL CONFIG]
MAX_QUEUED_JOBS = 1000
# enable virtualization
ENABLE_VIRT = false
# salt for password/encryption
PASSWORD_SALT = "abcd"

[API_SERVER]
# API workers
API_WORKERS = 8
# API server listen ip
API_SERVER_LISTEN_IP = "0.0.0.0"
# API server listen port
API_SERVER_LISTEN_PORT = 18400

[LOG]
# api log file
API_LOG_FILE = "/var/log/qcos/qcos-api.log"
# prefect log file
PREFECT_LOG_FILE = "/var/log/qcos/qcos-prefect.log"
# log format
LOG_FORMAT = "%(asctime)s | %(levelname)s | %(module)s:%(lineno)s %(message)s"
# log rotate, max_size (MB). default: 10MB
LOG_ROTATE_MAX_SIZE_MB = 10
# log rotate, backup count. default: 10
LOG_ROTATE_BACKUP_COUNT = 10
# log rotate, compression. default: true
LOG_ROTATE_COMPRESSION = true

[SSL]
# Enable HTTPS for API server
USE_SSL = false

# SSL CERT_FILE
# eg. CERT_FILE = "/etc/qcos/ssl/ssl.crt"
# CERT_FILE =

# SSL KEY_FILE
# eg. KEY_FILE = "/etc/qcos/ssl/ssl.key"
# KEY_FILE =

# SSL CACERT_FILE (Optional)
# eg. CACERT_FILE = "/etc/qcos/ssl/cacert.pem"
# CACERT_FILE =

[DEVICES]
# DEVICE_LIST example:
# DEVICE_LIST = ["dummy", "hanyuan1", "tiangong100", "tiangong1000", "spinq_rpc", "qiskit_aer_sim", "qiskit_qasm_sim"]
DEVICE_LIST = ["dummy"]
