# This workflow will build, publish and test the following images: sandbox/qcos/qcos-cli docker
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build/Publish/Test QCOS docker image

on:
  push:
    branches: [ develop, test ]
    tags:
      - "v*"
  schedule:
    # trigger on every night (14:00 UTC / 22:00 CST)
    - cron: '0 14 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build-qcos-base-image:
    runs-on: ubuntu-latest
    container:
      image: openeuler/openeuler:24.03-lts
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install basic packages
        run: |
          yum install -y docker docker-compose rsync

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Run Integrated Build Script for base
        shell: bash
        run: |
          cd ./build-scripts
          source ./version
          cp ./env.template ./.env
          ./build-images.sh -b

      - name: Upload qcos-base Docker Image Artifact
        uses: actions/upload-artifact@v4
        with:
          name: qcos-base-image-artifact
          path: ./build-scripts/images/qcos-base-amd64-dev.tar.xz
          retention-days: 1

  build-and-push-sandbox:
    needs: build-qcos-base-image
    runs-on: ubuntu-latest
    container:
      image: openeuler/openeuler:24.03-lts
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install basic packages
        run: |
          yum install -y docker docker-compose rsync findutils

      - name: Download qcos-base Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: qcos-base-image-artifact
          path: ./build-scripts/images/

      - name: Load qcos-base Docker Image
        run: docker load -i ./build-scripts/images/qcos-base-amd64-dev.tar.xz

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.QCOS_DOCKERHUB_USERNAME }}
          password: ${{ secrets.QCOS_DOCKERHUB_TOKEN }}

      - name: Generate Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.QCOS_DOCKERHUB_USERNAME }}/qcos-sandbox
          tags: |
            type=raw,value=nightly,enable=${{ github.event_name == 'schedule' }}
            type=raw,value=nightly-{{date 'YYYYMMDD'}},enable=${{ github.event_name == 'schedule' }}
            type=semver,pattern={{version}}
            type=semver,pattern=latest

      - name: Run Integrated Build Script for sandbox
        shell: bash
        env:
          ALL_TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          cd ./build-scripts
          source ./version
          cp ./env.template ./.env
          ./build-images.sh -s -n
          TAG_LIST=$(echo "$ALL_TAGS" | xargs)
          echo "TAGS: $TAG_LIST"
          for full_tag in $TAG_LIST; do
            echo "Processing tag: $full_tag"
            docker tag qcos-sandbox:dev $full_tag
            docker push $full_tag
          done

  build-and-push-qcos:
    needs: build-and-push-sandbox
    runs-on: ubuntu-latest
    container:
      image: qcos/qcos-sandbox:latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Download qcos-base Docker Image Artifact
        uses: actions/download-artifact@v4
        with:
          name: qcos-base-image-artifact
          path: ./build-scripts/images/

      - name: Load qcos-base Docker Image
        run: docker load -i ./build-scripts/images/qcos-base-amd64-dev.tar.xz

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.QCOS_DOCKERHUB_USERNAME }}
          password: ${{ secrets.QCOS_DOCKERHUB_TOKEN }}

      - name: Generate Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.QCOS_DOCKERHUB_USERNAME }}/qcos
          tags: |
            type=raw,value=nightly,enable=${{ github.event_name == 'schedule' }}
            type=raw,value=nightly-{{date 'YYYYMMDD'}},enable=${{ github.event_name == 'schedule' }}
            type=semver,pattern={{version}}
            type=semver,pattern=latest

      - name: Run Integrated Build Script for qcos
        shell: bash
        env:
          ALL_TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          cd ./build-scripts
          source ./version
          cp ./env.template ./.env
          ./build-images.sh -q -n
          TAG_LIST=$(echo "$ALL_TAGS" | xargs)
          echo "TAGS: $TAG_LIST"
          for full_tag in $TAG_LIST; do
            echo "Processing tag: $full_tag"
            docker tag qcos:${QCOS_VERSION} $full_tag
            docker push $full_tag
          done  

  build-and-push-qcos-cli:
    needs: build-and-push-sandbox
    container:
      image: qcos/qcos-sandbox:latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.QCOS_DOCKERHUB_USERNAME }}
          password: ${{ secrets.QCOS_DOCKERHUB_TOKEN }}

      - name: Generate Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.QCOS_DOCKERHUB_USERNAME }}/qcos-cli
          tags: |
            type=raw,value=nightly,enable=${{ github.event_name == 'schedule' }}
            type=raw,value=nightly-{{date 'YYYYMMDD'}},enable=${{ github.event_name == 'schedule' }}
            type=semver,pattern={{version}}
            type=semver,pattern=latest

      - name: Run Integrated Build Script for qcos-cli
        shell: bash
        env:
          ALL_TAGS: ${{ steps.meta.outputs.tags }}
        run: |
          cd ./build-scripts
          source ./version
          cp ./env.template ./.env
          ./build-images.sh -c -n
          TAG_LIST=$(echo "$ALL_TAGS" | xargs)
          echo "TAGS: $TAG_LIST"
          for full_tag in $TAG_LIST; do
            echo "Processing tag: $full_tag"
            docker tag qcos-cli:${QCOS_VERSION} $full_tag
            docker push $full_tag
          done  

  run-tests-qcos:
    needs: build-and-push-sandbox
    runs-on: ubuntu-latest
    container:
      image: qcos/qcos-sandbox:latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Unit Tests
        shell: bash
        run: |
          cicd/run-tests.sh -c all
          ls cicd/

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.QCOS_CODECOV_TOKEN }}
          files: cicd/coverage.xml

  run-tests-qcos-cli:
    needs: build-and-push-sandbox
    runs-on: ubuntu-latest
    container:
      image: qcos/qcos-sandbox:latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Unit Tests
        shell: bash
        run: |
          cicd/run-tests.sh -e all
